source/databases/access_db.html.haml
* suffixing .html to the links was required locally in
"middleman server" mode
=> fix MySQL link name, list links and list rendering

_includes/nav.html, _includes/search.html, _sass/header.sass
- Logo now links to Homepage
- Homepage link removed from header subnav
- Banner title: "Scalingo Documentation" -> "Documentation Center"
- Header subnav links: reduced font-weight
=> Header modifications

_posts/platform/deployment/buildpacks/2000-01-01-nginx.md, _posts/platform/deployment/buildpacks/2000-01-01-ssh-key.md
Fix #228
https://documentation-service-pr352.scalingo.io/platform/deployment/buildpacks/nginx
=> Add nginx buildpack documentation

_posts/languages/nodejs/2000-01-01-start.md
Fix #227 
https://documentation-service-pr353.scalingo.io/languages/nodejs/start#custom-cache-folder
@Soulou I am not sure this is what you meant for this issue. If it is, what is the purpose of customizing this folder?
=> Doc custom Node.js cache folder

_posts/platform/internals/2000-01-01-router-error-codes.md
https://documentation-service-pr373.scalingo.io/platform/internals/router-error-codes
Fix #363
=> Explain HTTP 502 in router error codes page

_posts/languages/ruby/rails/2000-01-01-start.md
https://documentation-service-pr426.scalingo.io/languages/ruby/rails/start#specifying-a-custom-nodejs-runtime
Fix #418
=> customize Node.js version when using Ruby buildpack

_posts/platform/app/2000-01-01-postdeploy-hook.md
Fix #432 
https://documentation-service-pr433.scalingo.io/platform/app/postdeploy-hook#notifying-external-service
=> Update the method to notify AppSignal of deploy

_posts/platform/app/2000-01-01-sticky-sessions.md
Fix #431
https://documentation-service-pr434.scalingo.io/platform/app/sticky-sessions#sticky-session-cookie
=> Clarify sticky session cookie working

_posts/platform/getting-started/2000-01-01-heroku-compatibility.md
=> Mention the 'release' vs postdeploy entry in heroku compatibility page

index.md
I am wondering whether it is possible to open the designated entry when it's targeted by an anchor link
http://documentation-service-pr453.scalingo.io/
Fix #448
=> Links to changelog with anchor

_config.yml
Fix #493 
https://documentation-service-pr495.scalingo.io/
=> Fix link on index to the Python getting started

_includes/encryption_at_rest.md, _posts/databases/elasticsearch/2000-01-01-start.md, _posts/databases/influxdb/2000-01-01-start.md, _posts/databases/mongodb/2000-01-01-start.md, _posts/databases/mysql/2000-01-01-start.md, _posts/databases/postgresql/2000-01-01-start.md, _posts/databases/redis/2000-01-01-start.md
https://documentation-service-pr491.scalingo.io/databases/postgresql/start#manual-database-backup
I'm not really satisfied with the location of this new bloc but I don't know where to put it....
Related to Scalingo/homepage#739
Fix #490
=> Mention on all DBs pages that we have encryption at rest by default

_posts/platform/deployment/2000-01-01-deploy-scalingo-from-bitbucket.md
https://documentation-service-pr532.scalingo.io/platform/deployment/deploy-scalingo-from-bitbucket
Fix #530 
I uploaded an image on the CDN but the image URL (https://cdn.scalingo.com/documentation/screenshot_bitbucket_deployment_event.png) returns Access Denied. I don't remember what has to be done to prevent this error... I made the image completely public on S3.
=> Add instructions to make use of Bitbucket Deployment Pipelines to deploy on Scalingo

changelog/databases/_posts/2019-04-16-redis-5.0.4.markdown, changelog/features/_posts/2019-04-12-alerts-duration.markdown
https://documentation-service-pr554.scalingo.io/changelog
=> [changelog] Announce Redis 5.0.4 and alerts duration before trigger

_posts/languages/nodejs/2000-01-01-start.md
Fix #546
https://documentation-service-pr562.scalingo.io/languages/nodejs/start#nodejs-build-hooks
=> Document NPM_NO_BUILD for Node.js apps

_posts/languages/python/django/2000-01-01-start.md
replace 'pip freeze > requirement.txt'
with
'pip freeze > requirements.txt'
=> Fix typo line 80: missing plural for 'requirement'

_posts/addons/scalingo-docker-image/2000-01-01-start.md
=> Docker Image addon uses the API token and not API key

_posts/platform/internals/2000-01-01-network.md
Some IT support don't know .0 is not a significative information
=> Use a valid CIDR format

_posts/languages/nodejs/2000-01-01-start.md
https://documentation-service-pr633.scalingo.io/languages/nodejs/start#framework-requiring-to-serve-static-files
Fix #590
Fix #631
=> JS frameworks which needs static files serving

changelog/databases/_posts/2019-12-11-patroni-1-6-3.markdown
New PostgreSQL versions:
- 10.11.0-2
- 11.6.0-2
- 12.1.0-4 
Tweet:
> [Changelog] Databases - PostgreSQL - New versions available: 10.11.0-2, 11.6.0-2 and 12.1.0-4 which include Patroni update 1.6.3 https://doc.scalingo.com/changelog #postgresql #patroni #changelog #paas
=> [changelog] Patroni 1.6.3

_posts/platform/getting-started/2000-01-01-getting-started-with-metabase.md
I placed this article in Platform > Getting Started just like the article to deploy ELK on Scalingo. But I'm not sure it's the best place. Maybe Platform > Deployment is a better place for both these articles? Same question as on #779 
Fix #704
=> Deploy Metabase on Scalingo

changelog/buildpacks/_posts/2019-12-20-nginx-1.17.6.markdown
Related to https://github.com/Scalingo/nginx-buildpack/issues/9
Tweet:
> [Changelog] Buildpacks - Nginx - Support of Nginx 1.17.6 https://changelog.scalingo.com #nginx #changelog #PaaS
=> [changelog] Nginx 1.17.6

_posts/languages/go/2000-01-01-start.md, changelog/buildpacks/_posts/2019-12-23-go-1.13.5.markdown
Tweet:
> [Changelog] Buildpacks - Go - New Versions: 1.13.5 and 1.12.14. 1.12.14 is the
> new default. https://changelog.scalingo.com #golang #changelog #PaaS #upgrade
=> [changelog] Go 1.13.5 and 1.12.14

changelog/databases/_posts/2019-12-24-elasticsearch-5.6.16-1.markdown
Tweet:
> [Changelog] Databases - Elasticsearch - New version is now available: 5.6.16-1. 5.6.x reached end of life, you should upgrade to the next major version https://changelog.scalingo.com #elasticsearch #paas #changelog #update
=> [changelog] Elasticsearch 5.6.16-1

_posts/languages/php/2000-01-01-start.md, changelog/buildpacks/_posts/2019-12-24-php-7.4.1.markdown
Tweet:
> [Changelog] Buildpacks - PHP - Support of PHP 7.4.1, 7.3.13 and 7.2.26 https://changelog.scalingo.com #php #changelog #PaaS
Fix https://github.com/Scalingo/php-buildpack/issues/114
=> [changelog] PHP 7.4.1, 7.3.13 and 7.2.26

changelog/base_image/_posts/2019-12-24-scalingo-14-v32-scalingo-18-v11.markdown
Tweet:
> [Changelog] Stacks - Both stacks include Bazaar and Mercurial CLI tools. https://changelog.scalingo.com #stacks #changelog #PaaS #upgrade
=> [changelog] scalingo-14:v32 and scalingo-18:v11

changelog/databases/_posts/2019-12-24-mongo-4.0.14-1.markdown, changelog/databases/_posts/2019-12-30-mongo-4.0.14-1.markdown
Tweet:
> [Changelog] - Databases - MongoDB - New default version: 4.0.14-1 -
> https://changelog.scalingo.com #mongodb #changelog #PaaS
=> [changelog] MongoDB 4.0.14-1

_includes/upon_request.md, _posts/platform/app/2000-01-01-autoscaler.md
fix #794
Motivation: as seen by the emails sent by some customers asking to get access to the feature, the "beta" tag is too deceptive. It implies a lack of stability which is not the case here.
=> make autoscaling available upon request instead of private beta 

_posts/languages/php/2000-01-01-start.md, changelog/buildpacks/_posts/2020-01-27-php-7.4.2.markdown
Tweet:
> [Changelog] Buildpacks - PHP - Support of PHP 7.4.2, 7.3.14 and 7.2.27 https://changelog.scalingo.com #php #changelog #PaaS
Fix Scalingo/php-buildpack#124
=> [changelog] PHP 7.4.2, 7.3.14 and 7.2.27

changelog/databases/_posts/2020-02-03-mongo-4.0.16-1.markdown
Tweet:
> [Changelog] - Databases - MongoDB - New default version: 4.0.16-1 - https://changelog.scalingo.com #mongodb #changelog #PaaS
=> [changelog] MongoDB 4.0.16-1

changelog/databases/_posts/2020-02-14-postgresql-12.2.0.markdown
Tweet:
> [Changelog] - Databases - PostgreSQL - New versions: 9.6.17, 10.12, 11.7 and 12.2 - https://changelog.scalingo.com #postgresql #changelog #PaaS
=> [changelog] PostgreSQL 12.2.0-1, 11.7.0-1, 10.12.0-1 and 9.6.17-1

README.md, _posts/platform/deployment/2000-01-01-deploy-from-archive.md, _posts/platform/deployment/2000-01-01-deploy-java-jar-war.md
The page was really outdated, we have the Scalingo CLI to handle archive deployments now:
https://documentation-service-pr837.scalingo.io/platform/deployment/deploy-from-archive
Fix #836
=> Deploy an archive using the CLI

_posts/languages/php/2000-01-01-start.md, changelog/buildpacks/_posts/2020-03-02-php-7.4.3.markdown
Tweet:
> [Changelog] Buildpacks - PHP - Support of PHP 7.4.3, 7.3.15 and 7.2.28 https://changelog.scalingo.com #php #changelog #PaaS
=> [changelog] PHP 7.4.3, 7.3.15 and 7.2.28

changelog/api/_posts/2020-01-03-notifications-path-deprecation.md
I just imported the last entry of the developers documentation. It's kind of annoying to manually import all the entries...
Related to https://github.com/Scalingo/developers-documentation/pull/81
=> Add last changelog of the dev doc changelog

_posts/languages/php/2000-01-01-start.md
`.config.platform.php` is not meant for production usage:
https://getcomposer.org/doc/06-config.md#platform
> Lets you fake platform packages (PHP and extensions) so that you can emulate a production env
=> Specifying the PHP version is done via .require.php

changelog/databases/_posts/2020-03-24-redis.5.0.8-1.markdown
Tweet:
> [Changelog] - Databases - Redis - New default version: 5.0.8-1 - https://changelog.scalingo.com #redis #changelog #PaaS
=> [changelog] Redis 5.0.8-1

changelog/buildpacks/_posts/2020-04-01-ruby-2.7.1.md
Tweet:
> [Changelog] Buildpacks - Ruby - Support of Ruby 2.7.1, 2.6.6, 2.5.8 and 2.4.10 https://changelog.scalingo.com #php #changelog #PaaS
=> [changelog] Ruby 2.7.1, 2.6.6, 2.5.8, 2.4.10

changelog/databases/_posts/2020-04-16-elasticsearch-6.8.6-2.markdown, changelog/databases/_posts/2020-04-16-postgresql-12.2.0-2.markdown
Tweets:
> [Changelog] - Databases - PostgreSQL - New default version: 12.2.0-2 - https://changelog.scalingo.com #postgresql #changelog #PaaS
> [Changelog] - Databases - Elasticsearch - New default version: 6.8.6-2 - https://changelog.scalingo.com #postgresql #changelog #PaaS
=> [changelog] PostgreSQL 12.2.0-2 and Elasticsearch 6.8.6-2

changelog/databases/_posts/2020-04-17-postgresql-12.2.0-3.markdown
> [Changelog] - Databases - PostgreSQL - New default version: 12.2.0-3 - https://changelog.scalingo.com #postgresql #changelog #PaaS
Related to https://github.com/Scalingo/one-stop-shop/issues/89
=> [changelog] PostgreSQL 12.2.0-3

_posts/platform/deployment/buildpacks/2000-01-01-multi.md
Part of fix for https://github.com/Scalingo/one-stop-shop/issues/28
=> Add node in documentation saying the multi-buildpack is now detected by default, no more need for BUILDPACK_URL

changelog/buildpacks/_posts/2020-04-24-multi-buildpack.markdown
Part of fix for https://github.com/Scalingo/one-stop-shop/issues/28
=> Changelog entry announcing the default support for the multi-buildpack

_posts/languages/go/2000-01-01-start.md, changelog/buildpacks/_posts/2020-04-28-go-1.14.2.markdown
Tweet:
> [Changelog] Buildpacks - Go - Support of Go 1.14.2, 1.13.10 and 1.12.17. 1.12.17 is the new default https://changelog.scalingo.com #golang #changelog #PaaS
=> [changelog] Go 1.14.2, 1.13.10 and 1.12.17

changelog/cli/_posts/2020-05-15-1-17-0.md
Tweet:
> [Changelog] CLI - Release of version 1.17.0 https://cli.scalingo.com - More news at https://changelog.scalingo.com #cli #paas #changelog #bugfix
=> [changelog] CLI 1.17.0

_posts/platform/cli/2000-01-01-start.md, _posts/platform/deployment/2000-01-01-deploy-java-jar-war.md
- Remove the title "Install Scalingo CLI" from "Deploy JAR/WAR" page (https://doc.scalingo.com/platform/deployment/deploy-java-jar-war#install-scalingo-cli)
- Add a title "Install Scalingo CLI" on the CLI page https://doc.scalingo.com/platform/cli/start
Related to #419
=> Second attempt at improving the Scalingo CLI SEO in Algolia search bar

_posts/platform/app/2000-01-01-ssl.md
Fix #986 
I used https://en.wikipedia.org/wiki/X.509#Certificate_filename_extensions as a source for my informations, as well as https://stackoverflow.com/questions/642284/do-i-need-to-convert-cer-to-crt-for-apache-ssl-certificates-if-so-how for the convert command.
=> Domains: clarify a few things about custom certificates

_posts/addons/tcp-gateway/2000-01-01-start.md
I recently managed to deploy a gRPC server on your infra with the help of @ksol on Intercom. I figured it’d be great to document that it’s possible and the few gotchas to know about.
In the paragraph, I am referencing informations from  https://github.com/Scalingo/documentation/pull/973. You might want to wait for it to be merged before merging this one.
=> Add gRPC section in TCP-Gateway docs

app/javascript/js/search.js
#992 introduced a bug described in (https://github.com/Scalingo/one-stop-shop/issues/145). What I changed is that we actully need to update the `window.location`, even in prod. Otherwise nothing happens when clicking on a search suggestion.
Related to https://github.com/Scalingo/one-stop-shop/issues/145
=> [Search] Always update the window.location even in prod

_posts/platform/internals/2000-01-01-network.md
I fixed a typo, and reordered the outgoing IPs information to have osc-fr1 first
=> [Outgoing IP] Typo + reorder

changelog/databases/_posts/2020-02-03-mongo-4.0.19-1.markdown
Tweet:
> [Changelog] - Databases - MongoDB - New default version: 4.0.19-1 - https://changelog.scalingo.com #mongodb #changelog #PaaS
=> [changelog] MongoDB 4.0.19-1 and 3.6.19

_posts/platform/app/2000-01-01-procfile.md
Add a block of text to prevent two targets in a procfile
Code followup: https://github.com/Scalingo/api/issues/1747
=> Add a note to inform that procfiles do not accepte multiple same name rules

changelog/buildpacks/_posts/2020-08-06-default-meteor-nodejs.markdown
Tweet:
> [Changelog] Buildpacks - Node.js - Node.js 12 by default for Meteor 1.9 and 1.10 https://changelog.scalingo.com #Node.js #changelog #PaaS
=> [changelog] Node.js buildpack update

changelog/databases/_posts/2020-08-28-postgresql-12.4.0-1.markdown
Tweet:
> [Changelog] - PostgreSQL - New default version: 12.4.0-1 - https://changelog.scalingo.com #postgresql #changelog #PaaS
=> [changelog] PostgreSQL 12.4.0-1, 11.9.0-1, 10.14.0-1 and 9.6.19

_posts/platform/app/2000-01-01-static-files-hosting.md
I was trying to deploy a static site with the package.json supplied in the doc and I ran into these errors : 
```
!   Error deploying the application
!   → Your application has stopped unexpectedly with the following output:
======== BEGIN OUTPUT ========
2020-06-25 12:01:57.665669761 +0000 UTC [web-1] npm ERR! Invalid name: "Test deploy Storybook"`
```
-> The name attribute doesn't allow spaces or capital letters
```
!   Error deploying the application
!   → Your application has stopped unexpectedly with the following output:
======== BEGIN OUTPUT ========
2020-06-25 12:04:25.075129456 +0000 UTC [web-1] npm ERR! Invalid version: "1.0"
```
-> The version attribute takes semver valid version: eg. 1.0.0
=> [DOC] Edit sample package.json with node v12 valid values

changelog/databases/_posts/2020-09-22-postgresql-10.14.0-2.markdown
Tweet:
> [Changelog] - PostgreSQL - New version: 10.14.0-2 - https://changelog.scalingo.com #postgresql #changelog #PaaS
=> [changelog] PostgreSQL 10.14.0-2

_posts/platform/internals/2000-01-01-container-management.md
The documentation page actually already talks about the restart operation. I just added a mention of the scale operation to make it clear that it works the same way in case of a scale oepration
Fix #957
=> Add scale operation

_posts/platform/getting-started/2000-01-01-getting-started-with-wordpress.md, redirections.yml
Redirection: https://documentation-service-pr1071.osc-fr1.scalingo.io/languages/php/wordpress
New link: https://documentation-service-pr1071.osc-fr1.scalingo.io/platform/getting-started/getting-started-with-wordpress
Fix #983
=> Move WordPress page to Getting Started section

changelog/databases/_posts/2020-10-08-mysql-5.7.31-1.markdown
Tweet:
> [Changelog] - MySQL - New default version: 5.7.31-1 - https://changelog.scalingo.com #mysql #changelog #PaaS
=> [changelog] MySQL 5.7.31-1 and 5.6.49-1

_posts/platform/databases/2000-01-01-restore-backup.md
https://documentation-service-pr1093.osc-fr1.scalingo.io/platform/databases/restore-backup#top-of-page
Fix #890
=> Add internal link from the generic restore backup page

changelog/buildpacks/_posts/2020-10-30-php-composer-configurable.markdown
Tweet:
> [Changelog] Buildpacks - PHP - Composer version is now configurable https://changelog.scalingo.com #php #changelog #PaaS
=> [changelog] PHP Composer version is configurable

changelog/databases/_posts/2020-11-16-postgresql-12.5.0-1.markdown
Tweet:
> [Changelog] - PostgreSQL - New default version: 12.5.0-1 - https://changelog.scalingo.com #postgresql #changelog #PaaS
=> [changelog] PostgreSQL 12.5.0-1, 11.10.0-1, 10.15.0-1 and 9.6.20

changelog/databases/_posts/2020-11-20-mysql-5.7.32-1.markdown
Tweet:
> [Changelog] - MySQL - New default version: 5.7.32-1 - https://changelog.scalingo.com #mysql #changelog #PaaS
=> [changelog] MySQL 5.7.32-1 and 8.0.22

_posts/platform/deployment/buildpacks/2000-01-01-nginx.md
This is no longer true since the introduction of the `servers.conf.erb` configuration file
=> Remove false information about instructions at the http level

_posts/platform/getting-started/2000-01-01-troubleshooting-ssh.md
Adding an indication to think about ensuring the branch name is master (an alternative error that provides the same error message)
=> Failed push refs: no master error

_posts/platform/getting-started/2000-01-01-getting-started-with-sonarqube.md
Related to https://github.com/Scalingo/sonarqube-buildpack/pull/2
=> [SonarQube] New default version is 8.6.0.39681

_posts/languages/python/django/2000-01-01-start.md
=> [Django] Use os.environ which raises a KeyError rather than os.getenv

_posts/languages/python/django/2000-01-01-start.md
Add a section that explains how to add `compilemessages` command section in django getting-started-tutorial.
=> Django getting-started-tutorial - compilemessages section

_posts/languages/php/2000-01-01-start.md, changelog/buildpacks/_posts/2021-02-03-php-7.4.14.markdown
Tweet:
> [Changelog] Buildpacks - PHP - Support of PHP 7.4.14 and 7.3.26 https://changelog.scalingo.com #php #changelog #PaaS
Fix https://github.com/Scalingo/php-buildpack/issues/177 / [OPSB-189]
[OPSB-189]: https://scalingo.atlassian.net/browse/OPSB-189
=> [changelog] PHP 7.4.14 and 7.3.26

_posts/languages/ruby/2000-01-01-start.md, changelog/buildpacks/_posts/2021-02-03-ruby-3.0.0.md
Tweet:
> [Changelog] Buildpacks - Ruby - New major version support - Support of Ruby 3.0.0 https://changelog.scalingo.com #ruby #changelog #PaaS
Fix [OPSB-225]
[OPSB-225]: https://scalingo.atlassian.net/browse/OPSB-225
=> docs(Ruby): announce Ruby 3.0.0 release

changelog/databases/_posts/2021-03-01-mysql-5.6.51-1.markdown
Tweet:
> [Changelog] - MySQL - New versions: 5.6.51-1, 5.7.33-1 and 8.0.23-1. 5.7.33-1 is the new default - https://changelog.scalingo.com #mysql #changelog #PaaS
=> [changelog] MySQL 5.6.51-1, 5.7.33-1 and 8.0.23-1

_posts/languages/python/2000-01-01-start.md, changelog/buildpacks/_posts/2021-03-01-python.markdown
Tweet:
> [Changelog] Buildpacks - Python - Support of Python 3.9.2, 3.8.8, 3.7.10 and 3.6.13 https://changelog.scalingo.com #python #changelog #PaaS
Related to https://github.com/Scalingo/python-buildpack/issues/14
=> docs(changelog): add support for Python 3.9.2, 3.8.8, 3.7.10 and 3.6.13

_posts/languages/php/2000-01-01-start.md
Since we've rebuilt all dependencies of PHP, the `gmp` extension now build successfuly for PHP 8
It seems it was a problem of version of the `libgmp` which got updated now.
=> GMP is now accessible for PHP 8

_posts/platform/getting-started/2000-01-01-getting-started-with-elk.md
There is a dependency error problem with version 5.8.1:
https://github.com/elastic/curator/issues/1560
https://github.com/elastic/curator/issues/1496
This is fixed in the new version 5.8.2
=> Update curator version

changelog/databases/_posts/2021-03-23-postgresql-12.6.0-1.markdown
Tweet:
> [Changelog] - PostgreSQL - New default version: 12.6.0-1 - https://changelog.scalingo.com #postgresql #changelog #PaaS
=> docs(changelog): PostgreSQL 12.6.0-1, 11.11.0-1, 10.16.0-1

_posts/platform/deployment/2000-01-01-deploy-with-git.md
`git push --force scalingo <commit ID>:master` failes with "error: The destination you provided is not a full refname". `git push --force scalingo <commit ID>:refs/heads/master` works though.
=> Correct git command for deploying a previous version

changelog/cli/_posts/2021-04-01-1-20-0.md
Tweet:
> [Changelog] CLI - Release of version 1.20.0 https://cli.scalingo.com - More news at https://changelog.scalingo.com #cli #paas #changelog
=> docs(changelog): release CLI 1.20.0

changelog/cli/_posts/2021-04-16-1-20-1.md
Tweet:
> [Changelog] CLI - Release of version 1.20.1 https://cli.scalingo.com - More news at https://changelog.scalingo.com #cli #paas #changelog #bugfix
=> docs(changelog): release CLI 1.20.1

_posts/languages/php/2000-01-01-start.md
We did not deprecated composer 1.x before the end of 2020.
=> Removing mention of composer 1.X deprecation for 2020

changelog/databases/_posts/2021-05-04-redis.6.2.3-1.md
Tweet:
> [Changelog] - Redis - New default version: 6.2.3-1 - https://changelog.scalingo.com This release contains a security fix, please upgrade as soon as possible. #redis #changelog #PaaS
=> docs(changelog): Redis 6.2.3-1

_posts/languages/php/2000-01-01-start.md, changelog/buildpacks/_posts/2021-05-11-php-composer-2-default.markdown
Related to https://github.com/Scalingo/php-buildpack/issues/168
=> docs(changelog): Composer 2.x is the new default

changelog/databases/_posts/2021-05-19-postgresql-12.7.0-1.md
Tweet:
> [Changelog] - PostgreSQL - New default version: 12.7.0-1 - https://changelog.scalingo.com #postgresql #changelog #PaaS
Related to https://github.com/Scalingo/appsdeck-database/issues/1985
=> docs(changelog): PostgreSQL 12.7.0-1, 11.12.0-1, 10.17.0-1 and 9.6.22-1

_posts/languages/php/2000-01-01-ips-filtering.md
The current way worked well for application without a framework but would fail for Symfony apps.
Since the allow and deny instructions are allowed on a server block, it might be better to put it there since it will have the same result without the potential conflict.
=> PHP: Do not add another / location

changelog/cli/_posts/2021-05-27-1-20-2.md
https://github.com/Scalingo/cli/releases/tag/1.20.2
Tweet:
> [Changelog] CLI - Release of version 1.20.2 https://cli.scalingo.com - More news at https://changelog.scalingo.com #cli #paas #changelog #bugfix
=> docs(changelog): release CLI 1.20.2

_posts/languages/ruby/2000-01-01-start.md
JRuby was never used/tested, thus we don't support it officially.
=> Update ruby versions to match currently supported version, remove jruby

_posts/languages/erlang/2000-01-01-start.md, changelog/buildpacks/_posts/2021-06-01-otp-24.md
Fix https://github.com/Scalingo/erlang-buildpack/issues/10
=> docs(changelog): release OTP 22.3.4.18, 23.3.4 and 24.0.1

_posts/languages/php/2000-01-01-start.md, changelog/buildpacks/_posts/2021-06-07-php-8.0.7.markdown
Tweet:
> [Changelog] Buildpacks - PHP - Support of PHP 8.0.7, 7.4.20 and 7.3.28 https://changelog.scalingo.com #php #changelog #PaaS
Fix https://github.com/Scalingo/php-buildpack/issues/201
=> docs(changelog): PHP 8.0.7, 7.4.20 and 7.3.28

changelog/databases/_posts/2021-07-08-elasticsearch-6.8.17-1.md
Tweet:
> [Changelog] - Elasticsearch - New default version: 6.8.17-1 - https://changelog.scalingo.com #elasticsearch #changelog #PaaS
=> docs(changelog): Elasticsearch 6.8.17

_posts/databases/postgresql/2000-01-01-extensions.md, changelog/databases/_posts/2021-07-08-postgresql-13.3.0-1.md
Tweet:
> [Changelog] - PostgreSQL - New major version: 13.3.0-1 - https://changelog.scalingo.com #postgresql #changelog #PaaS
=> docs(postgresql): update extensions version and release PostgreSQL 13

changelog/databases/_posts/2021-07-27-redis.6.2.5-1.md
Tweet:
> [Changelog] - Redis - New security release: 6.2.5-1 and 5.0.13-1 - https://changelog.scalingo.com #redis #changelog #PaaS
=> docs(changelog): Redis 6.2.5-1 and 5.0.13-1

.yarnrc, Dockerfile, docker-compose.yml
* Add `.yarnrc` to ignore dependency package.json engines constraint
* Ensure the PATH in the docker setup is good since apt package yarn
include nodejs 10 but we want to be explicit on the version
* Fix docker-compose.yml to ensure webpacker is getting the gems from
the right directory for ruby 3
=> feat(dev-setup) Fix development setup followign dependabot breakage

.github/dependabot.yml
We'd be better off catching up this ecosystem by hand first, dependabot is not well suited for catching up months/years of lateness. It is more error-prone / env-breaking prone than anything else at the moment
=> Remove dependabot for js deps

_posts/platform/internals/2000-01-01-routing.md
Internal reference: https://github.com/Scalingo/scalingo-openresty/blob/master/nginx-prod.conf#L93
=> Let's display the reality, the read timeout is 60s for at least 3-4 years

_posts/languages/java/2000-01-01-start.md, changelog/buildpacks/_posts/2021-09-14-java-openjdk-16.markdown
Related to https://github.com/Scalingo/buildpack-jvm-common/pull/27
Tweet:
```
[Changelog] Buildpacks - Java - Support for JDK 16 https://changelog.scalingo.com #java #jdk #changelog #PaaS
```
=> docs(java): JDK 16 support

_posts/languages/erlang/2000-01-01-start.md
The OTP we use has been dowgraded in https://github.com/HashNuke/heroku-buildpack-elixir-otp-builds/commit/c9d4faf8a2920fd43111a206b77beb6e29a77552. Let's only use the OTP versions described in https://github.com/HashNuke/heroku-buildpack-elixir-otp-builds/blob/master/otp-versions as per our internal documentation. It seems thos not in the `optp-versions` file have been porrly packaged
=> docs(erlang): downgrade some versions

_posts/languages/java/2000-01-01-start.md, changelog/buildpacks/_posts/2021-09-16-java-openjdk-17.markdown
Related to https://github.com/Scalingo/buildpack-jvm-common/pull/29
Tweet:
```
[Changelog] Buildpacks - Java - Support for JDK 17 LTS https://changelog.scalingo.com #java #java17 #jdk #changelog #PaaS
```
=> release(jdk): Add JDK 17 LTS support

_posts/platform/deployment/2000-01-01-deploy-with-github.md, _posts/platform/deployment/2000-01-01-deploy-with-gitlab.md
=> docs(scm): GitLab and GitHub Enterprise are now available via the dashboard

_posts/platform/app/2000-01-01-filesystem.md, _posts/platform/internals/2000-01-01-network.md
=> docs: replace links to Outscale doc to target the new doc

_posts/languages/php/2000-01-01-start.md, changelog/buildpacks/_posts/2021-11-30-php-8.1.0.md, changelog/buildpacks/_posts/2021-11-30-php-composer-2.1.14.md
> [Changelog] Buildpacks - PHP - Support of PHP 8.1.0 https://changelog.scalingo.com #php #changelog #PaaS
Related to https://github.com/Scalingo/php-buildpack/issues/222 and https://github.com/Scalingo/php-buildpack/issues/224
=> docs(changelog): PHP 8.1.0, 8.0.13, 7.4.26 and 7.3.33

_posts/languages/go/2000-01-01-start.md, changelog/buildpacks/_posts/2021-12-08-go-1.17.md
Related to https://github.com/Scalingo/go-buildpack/pull/15
I have included `go1.14.15` and `go1.13.15` (which is not part of the release) to the documentation that have been forgotten at a previous time
Tweet:
> [Changelog] Buildpacks - Go - Support of Go 1.17.3, 1.16.10 and 1.15.10 https://changelog.scalingo.com #golang #changelog #PaaS
=> release(go): Support for Go 1.17

_posts/languages/php/2000-01-01-start.md, changelog/buildpacks/_posts/2021-12-22-php-composer-2.2.0.md
Related to https://github.com/Scalingo/php-buildpack/issues/226
Tweet:
> [Changelog] Buildpacks - PHP - Support of Composer 2.2.0 https://changelog.scalingo.com #php #composer #changelog #PaaS
=> docs(changelog): Composer 1.10.24 and 2.2.0

_posts/platform/cli/2000-01-01-features.md, _posts/platform/deployment/buildpacks/2000-01-01-ssh-key.md, _posts/platform/getting-started/2000-01-01-first-steps.md, _posts/platform/getting-started/2000-01-01-setup-ssh-linux.md, _posts/platform/getting-started/2000-01-01-setup-ssh-macos.md, _posts/platform/getting-started/2000-01-01-setup-ssh-windows.md
Since DSA and RSA are slowly being rolled out of client implementations
=> SSH: Switch to ed25519 keys

_posts/languages/python/2000-01-01-start.md, changelog/buildpacks/_posts/2022-01-07-python-3.10.1.md
> [Changelog] Buildpacks - Python - Support of version 3.10.1, 3.9.9, 3.8.12, 3.7.12 and 3.6.15 https://changelog.scalingo.com #python #changelog #PaaS
Related to https://github.com/Scalingo/python-buildpack/pull/53
=> docs(python): add support for Python 3.10.1, 3.9.9, 3.8.12, 3.7.12 and 3.6.15

changelog/buildpacks/_posts/2022-01-12-php-apcu-ext-5.1.21.md, changelog/buildpacks/_posts/2022-01-12-php-composer-2.2.4.md
f51e38fc fix https://github.com/Scalingo/php-buildpack/issues/230
b14b9c66 fix https://github.com/Scalingo/php-buildpack/issues/228
Tweets
> [Changelog] Buildpacks - PHP - Support of Composer 2.2.4 https://changelog.scalingo.com #php #composer #changelog #PaaS
> [Changelog] Buildpacks - PHP - Support of extension APCU version 5.1.21 https://changelog.scalingo.com #php #PaaS #update #changelog
=> docs(changelog): new PHP Composer and APCU versions

changelog/cli/_posts/2022-01-17-1-22-1.md
Tweet:
> [Changelog] CLI - Release of version 1.22.1 https://cli.scalingo.com - More news at https://changelog.scalingo.com #cli #paas #changelog #bugfix
=> docs(changelog): CLI v1.22.1

_posts/databases/postgresql/2000-01-01-extensions.md, changelog/databases/_posts/2022-01-18-postgresql-12.9.0-1.md
Tweet:
> [Changelog] - PostgreSQL - New versions: 12.9.0-1, 11.14.0-1, 10.19.0-1 and 9.6.24-1 - https://changelog.scalingo.com #postgresql #changelog #PaaS
Second tweet in the same thread:
> PostgreSQL version 9.6.24-1 is the latest version of the 9.6 branch. It is end of life since 2021/11/11.
=> docs(changelog): PostgreSQL 12.9.0-1, 11.14.0-1, 10.19.0-1 and 9.6.24-1

_posts/platform/app/2000-01-01-environment.md
Not very clear to a customer if they have to use the `$` symbol to get the value from their application.
Also add an example with Shell and Java. And two missing env vars from the list: `STACK` and `REGION_NAME`
=> docs(environment): Few improvements on app env page

_posts/platform/app/2000-01-01-tasks.md
https://documentation-service-pr1526.osc-fr1.scalingo.io/platform/app/tasks#top-of-page
Fix #1487
=> docs(one-off): default size is M

_posts/platform/app/2000-01-01-app-with-gdal.md
https://documentation-service-pr1525.osc-fr1.scalingo.io/platform/app/app-with-gdal
Fix #1524
=> docs(gdal): add page to use GDAL in an app

_posts/databases/postgresql/2000-01-01-start.md
https://documentation-service-pr1532.osc-fr1.scalingo.io/databases/postgresql/start#running-queries
I'm not completely convinced by how the quote of the mailing list is displayed. WDYT? Should I paraphrase instead of quoting to improve the display? Or leave it as is?
Fix #1198
=> docs(postgresql): explain idle queries

_posts/platform/databases/2000-01-01-access.md
https://documentation-service-pr1531.osc-fr1.scalingo.io/platform/databases/access#manually-install-the-databases-cli-in-one-off
Fix #1407
=> docs(redis-cli): mention it's impossible to use if Force TLS is enabled

_posts/languages/nodejs/2000-01-01-deployment-errors.md
https://documentation-service-pr1544.osc-fr1.scalingo.io/languages/nodejs/deployment-errors#host-key-verification-failed
We already had this page https://www.notion.so/scalingooriginal/Node-js-Build-fail-with-Host-key-verification-failed-6d54223301f14a8fac7a6b93e043de1b
But I don't see why it should only be part of our internal documentation, as it is an issue with npm.
=> feat: add ssh node package issue

src/_posts/platform/deployment/buildpacks/2000-01-01-nginx.md
I'm not completely sure that it's what you meant in the related issue @brandon-welsch. Do you confirm it fixes the issue?
Fix #1408
=> docs(nginx): add proxy_redirect to split traffic between 2 APIs

src/_posts/databases/postgresql/2000-01-01-extensions.md, src/changelog/databases/_posts/2022-02-24-postgresql-13.6.0-3.md
Tweet:
> [Changelog] - PostgreSQL - New default version: 13.6.0-3 with TimescaleDB inside 🎉  - https://changelog.scalingo.com #postgresql #changelog #PaaS
=> docs(changelog): PostgreSQL 13.6.0-3

src/_posts/platform/app/2000-01-01-ffmpeg.md
The lower case spelling is probably for the executable
Related to https://github.com/Scalingo/ffmpeg-buildpack/issues/4
=> docs(ffmpeg): spell ffprobe -> FFprobe

src/_posts/languages/ruby/2000-01-01-start.md
=> docs(ruby): MRI 3.1.1 is available

src/changelog/buildpacks/_posts/2022-03-18-nodejs-16.md, src/changelog/buildpacks/_posts/2022-03-18-ruby.md
Tweets:
> [Changelog] Buildpacks - Node.js - New default version is 16.x https://changelog.scalingo.com #Node.js #changelog #PaaS
> [Changelog] Buildpacks - Ruby - Support of Ruby 3.1.1 and 3.0.3 https://changelog.scalingo.com #ruby #changelog #PaaS
Related to  Scalingo/ruby-buildpack#38 and Scalingo/nodejs-buildpack#54
=> docs(changelog): Ruby and Node.js updates

src/_posts/languages/ruby/2000-01-01-start.md, src/changelog/buildpacks/_posts/2022-04-06-ruby-bundler.md
Bundler versions: https://github.com/Scalingo/ruby-buildpack/blob/9e2d66620eed80bb2f8720c82add5fbc234fe063/lib/language_pack/helpers/bundler_wrapper.rb#L39-L40
=> docs(ruby): Update default Bundler versions

src/_posts/platform/databases/2000-01-01-access.md
Direct access was renamed to Internet Accessibility this change broke the link in this warning block.
This PR fix the link and the wording issue.
=> fix(db-access) Fix broken links and wording issues

src/_includes/adminer_endpoints.md, src/_includes/api_endpoints.md, src/_includes/db_api_endpoints.md, src/_includes/db_ca_endpoints.md, src/_includes/phpmyadmin_endpoints.md, src/_includes/ssh_endpoints.md, src/_includes/ssh_urls.md, src/_posts/databases/elasticsearch/2000-01-01-start.md, src/_posts/databases/influxdb/2000-01-01-start.md, src/_posts/databases/mongodb/2000-01-01-compass.md, src/_posts/databases/mongodb/2000-01-01-dump-restore.md, src/_posts/databases/mongodb/2000-01-01-robo3t.md, src/_posts/databases/mongodb/2000-01-01-start.md, src/_posts/databases/mysql/2000-01-01-dump-restore.md, src/_posts/databases/mysql/2000-01-01-start.md, src/_posts/databases/mysql/2000-01-01-workbench.md, src/_posts/databases/postgresql/2000-01-01-start.md, src/_posts/databases/redis/2000-01-01-start.md, src/_posts/platform/databases/2000-01-01-access.md, src/_posts/platform/databases/2000-01-01-adminer.md, src/_posts/platform/deployment/continuous-integration/2000-01-01-deploy-scalingo-from-bitbucket.md, src/_posts/platform/deployment/continuous-integration/2000-01-01-deploy-scalingo-from-semaphore-ci.md, src/_posts/platform/internals/2000-01-01-regions.md
A "little" PR of refactoring to have endpoints documented in multiple files but at one place.
Also updated a couple of URLs and make some improvements
=> docs(region-endpoints): Some refactoring to not have duplicated regions information everywhere

src/changelog/buildpacks/_posts/2022-04-28-php-imagick-ext-3.7.0.md
Tweet:
> [Changelog] Buildpacks - PHP - Support of extension imagick version 3.7.0 https://changelog.scalingo.com #php #imagick #PaaS #update #changelog
Related to https://github.com/Scalingo/php-buildpack/issues/247
=> docs(changelog): upgrade imagick 3.7.0

src/changelog/databases/_posts/2022-05-11-mysql-5.7.38-1.md
Tweet
> [Changelog] - MySQL - New default version: 5.7.38-1 - https://changelog.scalingo.com #mysql #changelog #PaaS
=> docs(changelog): MySQL 5.7.38-1

src/changelog/buildpacks/_posts/2022-05-12-php-ext-memcached-3.2.0.md
Tweet:
> [Changelog] Buildpacks - PHP - Support of extension memcached version 3.2.0 https://changelog.scalingo.com #php #memcached #PaaS #update #changelog
Related to https://github.com/Scalingo/php-buildpack/issues/243
=> docs(changelog): PHP extension memcached 3.2.0

src/_posts/languages/php/2000-01-01-start.md, src/changelog/buildpacks/_posts/2022-05-18-php-8.1.6.md
Tweet 
> [Changelog] Buildpacks - PHP - Support of PHP 8.1.6, 8.0.19 and 7.4.29 https://changelog.scalingo.com #php #changelog #PaaS
Fix https://github.com/Scalingo/php-buildpack/issues/229
=> docs(changelog): PHP 8.1.6, 8.0.19 and 7.4.29

src/changelog/databases/_posts/2022-05-19-influxdb-1.8.10.md
Tweet:
> [Changelog] - InfluxDB - New default version: 1.8.10-1 - https://changelog.scalingo.com #influxdb #changelog #PaaS
=> docs(changelog): InfluxDB 1.8.10-1

config.ru
`https://cli.scalingo.com` redirects to `https://doc.scalingo.com/platform/cli/start/` (404 error) instead of `https://doc.scalingo.com/platform/cli/start`
Fix consists of removing the trailing slash in the destination URI.
=> Fix cli.scalingo.com redirect issue 

src/_posts/languages/go/2000-01-01-gomod.md, src/_posts/languages/go/2000-01-01-start.md, src/changelog/buildpacks/_posts/2022-06-10-go-1.18.3.md
Tweet:
> [Changelog] Buildpacks - Go - Support of Go 1.18.3. https://changelog.scalingo.com #golang #changelog #PaaS
Fix https://github.com/Scalingo/go-buildpack/issues/23
Fix https://github.com/Scalingo/go-buildpack/issues/16
=> docs(changelog): Go 1.18.3

src/changelog/databases/_posts/2022-06-14-elasticsearch-6.8.23-1.md
Tweet:
> [Changelog] - Elasticsearch - New default version: 6.8.23-1 - https://changelog.scalingo.com #elasticsearch #changelog #PaaS
=> docs(changelog): Elasticsearch 6.8.23-1

src/changelog/cli/_posts/2022-06-15-1-23-0.md
Tweet:
> [Changelog] CLI - Release of version 1.23.0 https://cli.scalingo.com - More news at https://changelog.scalingo.com #cli #paas #changelog #bugfix
=> docs(changelog): CLI v1.23.0

README.md, src/app/styles/index.postcss.css
[DOC-88]
Allows text to break on small screens.
Long wordings without space as DATABASE_URL=$SCALINGO_MONGO_URL in src/_posts/platform/app were enlarging their own box and text went outside of parents box.
[DOC-88]: https://scalingo.atlassian.net/browse/DOC-88?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: text won't break and enlarges box on mobile screen

src/_posts/languages/php/2000-01-01-start.md, src/changelog/buildpacks/_posts/2022-07-12-php-8.1.7.md
Updated documentation following the release of PHP:
- 7.4.30
- 8.0.20
- 8.1.7
Fixes https://github.com/Scalingo/php-buildpack/issues/256
=> docs(php-buildpack): release of PHP 7.4.30, 8.0.20 and 8.1.7

src/_posts/languages/php/2000-01-01-start.md
The existing instructions explaining how Composer version contraints
work were wrong or misleading. This commit modifies the instructions and
adds a link to the Composer documentation.
Fixes #1684
=> docs(languages/php): updated instructions about Composer constraints

src/_posts/languages/python/2020-11-23-SQLAlchemy.md
Fix #1686 
Related to https://github.com/Scalingo/python-buildpack/pull/46
To be sure I tested by using [Python buildpack's script](https://github.com/Scalingo/python-buildpack/blob/master/vendor/python.sqlalchemy.sh):
```bash
python-buildpack git:(master !) ➜ export SCALINGO_POSTGRESQL_URL=postgres://test:test@test.com:1234
python-buildpack git:(master !) ➜ set +x ./vendor/python.sqlalchemy.sh
++ env
++ awk -F = '{print $1}'
++ grep SCALINGO_POSTGRESQL_URL
+ for database_url_variable in $(env | awk -F "=" '{print $1}' | grep "SCALINGO_POSTGRESQL_URL")
++ eval echo '$SCALINGO_POSTGRESQL_URL'
+++ echo postgres://test:test@test.com:1234
+ set_sql_alchemy_url postgres://test:test@test.com:1234 SCALINGO_POSTGRESQL_ALCHEMY
+ local database_url=postgres://test:test@test.com:1234
+ local …
```
=> fix(sqlAlchemy): use the correct name of the variable

src/_posts/addons/scalingo-docker-image/2000-01-01-start.md
I noticed this following a support conversation
=> docs(docker): fix token creation link and login to registry

src/_posts/platform/getting-started/2000-01-01-getting-started-with-modsecurity.md
Add a Getting started with ModSecurity guide.
Most of the content is taken from https://github.com/Scalingo/nginx-buildpack
Fixes #1615
=> docs(documentation): add a getting started with modsecurity guide

src/_posts/languages/php/2000-01-01-laravel.md
The section of the Laravel documentation dedicated to the Laraval Task Scheduler
is outdated.
This patch fixes this by encouraging users to use the Scalingo
Scheduler. The old way to proceed is still documented for cases where
tasks need to run more frequently than once every 10 minutes.
Fixes #1680
=> docs(documentation): update Laravel documentation

src/changelog/databases/_posts/2022-08-05-redis.6.2.7-1.md
Tweet:
> [Changelog] - Redis - New versions: 6.2.7-1 and 5.0.14-1 - 6.2.7-1 is the new default - https://changelog.scalingo.com #redis #changelog #PaaS
=> docs(changelog): Redis 6.2.7-1 and 5.0.14-1

src/_posts/databases/mongodb/2000-01-01-compass.md
This reverts commit 97e7e1f88159821f29e3d5b65e17182f5a5ef17c from #1695
As highlighted by Brandon (https://github.com/Scalingo/documentation/pull/1695#issuecomment-1211927751), the fields are correct with the latest Compass version. Sorry for not checking my Compass version :/
=> Revert "docs(compass): update instructions to match new fields name"

src/changelog/cli/_posts/2022-09-26-1-25-1.md
Tweet:
> [Changelog] CLI - Release of version 1.25.1 https://cli.scalingo.com - More news at https://changelog.scalingo.com #cli #paas #changelog #bugfix
Related to https://github.com/Scalingo/cli/releases/tag/1.25.1
=> docs(changelog): CLI v1.25.1

src/changelog/cli/_posts/2022-10-07-1-26-0.md
Tweet:
> [Changelog] CLI - Release of version 1.26.0 https://cli.scalingo.com - More news at https://changelog.scalingo.com #cli #paas #changelog #bugfix
=> docs(changelog): CLI v1.26.0

src/_posts/languages/php/2000-01-01-start.md, src/changelog/buildpacks/_posts/2022-11-02-php-8.1.12.md, src/changelog/buildpacks/_posts/2022-11-02-php-composer-2.4.4.md
PHP updates for both `scalingo-18` and `scalingo-20`:
- 8.1.12
- 8.0.25
- 7.4.32
https://semver.scalingo.com/php-scalingo-18/resolve/~7.4
https://semver.scalingo.com/php-scalingo-18/resolve/~8.0
https://semver.scalingo.com/php-scalingo-18/resolve/~8.1
https://semver.scalingo.com/php-scalingo-20/resolve/~7.4
https://semver.scalingo.com/php-scalingo-20/resolve/~8.0
https://semver.scalingo.com/php-scalingo-20/resolve/~8.1
Files have been uploaded to the ObjectStorage.
Fixes https://github.com/Scalingo/php-buildpack/issues/263
=> chore(php): update PHP to 7.4.32, 8.0.25 and 8.1.12

src/_posts/languages/php/2000-01-01-start.md, src/changelog/buildpacks/_posts/2022-11-02-php-composer-2.4.4.md
Follow of the PHP Composer 2.4.4 upgrade:
https://semver.scalingo.com/composer-scalingo-18/resolve/2.x
https://semver.scalingo.com/composer-scalingo-20/resolve/2.x
Files have been uploaded to the ObjectStorage.
Fixes https://github.com/Scalingo/php-buildpack/issues/272
=> chore(php-composer): upgrade PHP Composer to 2.4.4

src/_posts/platform/app/2000-01-01-log-drain.md
This PR updates documentation about the new AppSignal compatibility and the token parameter for syslog (tcp+tls)
FIX #1779
=> docs(log-drains): update appsignal and syslog tcp+tls examples and parameters

src/_posts/platform/databases/2000-01-01-access.md
=> fix(ssh): fix example's command to build tunnel with OpenSSH

src/_posts/platform/getting-started/2000-01-01-getting-started-with-elk.md
The one-click button to deploy Kibana is provisioning a new Elasticsearch add-on. This may be confusing while the documentation indicates how to use the one that has been provisioned just before that with Logstash.
=> Add note about Kibana Elasticsearch add-on

src/_posts/platform/deployment/continuous-integration/2000-01-01-deploy-scalingo-from-gitlab.md
=> fix(dpl): freeze ruby version for dpl deployment

src/_posts/languages/ruby/2000-01-01-start.md, src/changelog/buildpacks/_posts/2022-12-29-ruby-3.2.0.md
Fix https://github.com/Scalingo/ruby-buildpack/issues/46
Tweet:
> [Changelog] Buildpacks - Ruby - Support of Ruby 3.2.0 https://changelog.scalingo.com #ruby #changelog #PaaS
=> docs(changelog): Ruby 3.2.0 is available

src/changelog/cli/_posts/2023-01-06-1-27-1.md
Related to https://github.com/Scalingo/cli/pull/864
=> Bump cli version to 1.27.1

src/_posts/platform/app/task-scheduling/2000-01-01-scalingo-scheduler.md
Fully reorganized/rewrote the documentation about the Scalingo Scheduler:
- I grouped the limitations in a single section ;
- I added the missing ones ;
- I re-phrased some sentences ;
- I ditch the FAQ (information have been dispatched in their sections).
I hope this will make things a bit clearer for the users.
=> fix(scalingo scheduler): update Scalingo Scheduler's doc

src/_posts/platform/app/task-scheduling/2000-01-01-custom-clock-processes.md
Fully reorganized/rewrote the documentation about Custom Clock Processes:
- I calked the page organization on my suggestions for the Scalingo Scheduler (see PR https://github.com/Scalingo/documentation/pull/1915)
- I specifically listed the differences with the Scalingo Scheduler
- I added some precisions about how they work
- I added a 'Costs' section
- I rephrased some explanations
- ...
I hope this will make things a bit clearer for the users.
=> fix(custom clock process): update Custom Clock Processes' doc

src/_posts/languages/java/2000-01-01-spring-boot.md, src/_posts/platform/databases/2000-01-01-restore-backup.md
It also contains some nitpicks following https://github.com/Scalingo/documentation/pull/1960
Fix #892
=> docs(database): download backup from one-off

src/_posts/security/bulletins/2023-01-01-SSB-2023-001.md
Make the document responsible on chrome
=> Shorten sec bulletins urls

src/_posts/databases/elasticsearch/2000-01-01-start.md, src/_posts/databases/influxdb/2000-01-01-start.md, src/_posts/databases/mongodb/2000-01-01-compass.md, src/_posts/databases/redis/2000-01-01-data-import.md, src/_posts/languages/meteorjs/2000-01-01-telescope.md, src/_posts/languages/python/django/2000-01-01-start.md, src/_posts/platform/app/2000-01-01-environment.md, src/_posts/platform/app/2000-01-01-scaling.md, src/_posts/platform/cli/2000-01-01-features.md, src/_posts/platform/deployment/2000-01-01-one-click-deploy.md, src/_posts/platform/deployment/continuous-integration/2000-01-01-deploy-scalingo-from-circle-ci.md, src/_posts/platform/getting-started/2000-01-01-getting-started-with-metabase.md
As a convention, the app options should be written as its long form.
And since CLI version upgrade, the order of the arguments has changed.
=> Fix documentation coherence, and wrong order of arguments

src/_posts/databases/postgresql/2000-01-01-dump-restore.md, src/_posts/databases/redis/2000-01-01-data-import.md, src/_posts/databases/redis/2000-01-01-dump-restore.md
- added a page `src/_posts/databases/redis/2000-01-01-dump-restore.md` which mimics the dump & restore page for other databases (e.g. https://doc.scalingo.com/databases/postgresql/dump-restore).
- updated the https://doc.scalingo.com/databases/redis/data-import page which contained outdated information.
Fix #1490
=> docs(Redis): instructions to dump

src/_posts/languages/php/2000-01-01-start.md, src/changelog/buildpacks/_posts/2023-02-24-php-8.0.28-8.1.16-8.2.3.md
Done for the following stacks:
- `scalingo-18`
* https://semver.scalingo.com/php-scalingo-18/resolve/~8.0
* https://semver.scalingo.com/php-scalingo-18/resolve/~8.1
* https://semver.scalingo.com/php-scalingo-18/resolve/~8.2 
- `scalingo-20`
* https://semver.scalingo.com/php-scalingo-20/resolve/~8.0
* https://semver.scalingo.com/php-scalingo-20/resolve/~8.1
* https://semver.scalingo.com/php-scalingo-20/resolve/~8.2
- `scalingo-22`
* https://semver.scalingo.com/php-scalingo-20/resolve/~8.1
* https://semver.scalingo.com/php-scalingo-20/resolve/~8.2
Files have been uploaded to ObjectStorage.
Fixes https://github.com/Scalingo/php-buildpack/issues/305
=> fix(php-buildpack): upgrade PHP to 8.0.28, 8.1.16 and 8.2.3

src/_posts/platform/deployment/continuous-integration/2000-01-01-deploy-scalingo-from-gitlab.md
=> docs(gitlab-ci): Add the Git Remote Already Exists Error

src/_posts/languages/python/2000-01-01-start.md, src/changelog/buildpacks/_posts/2023-03-09-python-3.11.2.md
Related to https://github.com/Scalingo/python-buildpack/issues/76
=> release(python-buildpack): Python 3.11 support and others version updates

src/_posts/languages/go/2000-01-01-start.md, src/changelog/buildpacks/_posts/2023-03-13-go-1.20.0.md
Tweet:
> [Changelog] Buildpacks - Go - Support of Go 1.20.0, 1.19.5 and 1.18.10 [https://changelog.scalingo.com](https://changelog.scalingo.com/) #golang #changelog #PaaS
=> docs(changelog): Go 1.20.0

src/_posts/platform/app/2000-01-01-procfile.md
Here is a suggestion for an almost complete rewrite of the Procfile documentation page.
- the content has been reorganized.
- explanations about "process type" have been added.
- explanations about Procfile have been added.
- references to "container" have been removed in favor of "Managed Runtime".
- ...
(When I first had to work with a Procfile, a lot of questions popped in my head. I think this would have answered them.)
Tested locally.
=> fix(procfile): update doc about Procfile

src/_posts/platform/app/2000-01-01-lifecycle-management.md
Replace old links pointing to my.scalingo.com with dashboard.scalingo.com.
=> fix: fix links pointing to 'my.scalingo.com'

src/_posts/platform/app/2000-01-01-tasks.md
When I try to use the `/tmp` directory I'm getting `Operation not permitted` errors.
=> Use app directory to extract tar

src/_posts/languages/nodejs/2000-01-01-start.md
Using with in `start` may crash the container currently
=> Vite note about vite compiling on the fly

src/_posts/databases/elasticsearch/2000-01-01-start.md, src/_posts/databases/influxdb/2000-01-01-start.md, src/_posts/databases/mongodb/2000-01-01-start.md, src/_posts/databases/mysql/2000-01-01-start.md, src/_posts/databases/postgresql/2000-01-01-start.md, src/_posts/databases/redis/2000-01-01-start.md
Added a note about this information because it can confuse some clients :
https://app.intercom.com/a/inbox/w4oogu7s/inbox/admin/5676128/conversation/12375700136909?view=List
=> docs(database upgrade): add a note explaining upgrade to minor version before accessing major

src/_posts/languages/php/2000-01-01-start.md
Update the doc related to PHP extensions:
- we support all PECL extensions.
- re-phrased some sentences.
=> fix(php-buildpack): update doc about PHP extensions

src/_posts/platform/app/task-scheduling/2000-01-01-scalingo-scheduler.md
Moved the paragraph explaining how to deal with multiple environments in its own section to better emphasis it.
Before it was in the "Disabling a Scheduled Task" section, and, thus, kind of hard to find.
=> fix(scalingo-scheduler): multiple environments doc

src/_posts/platform/app/2000-01-01-ffmpeg.md
Make sure `blas` and `lapack` are in `LD_LIBRARY_PATH`.
This seems required for ffmpeg to work.
Fixes https://github.com/Scalingo/php-buildpack/issues/321
=> fix(ffmpeg): update instructions for ffmpeg

src/_posts/addons/scalingo-openvpn/2000-01-01-start.md, src/_posts/languages/php/2000-01-01-start.md, src/_posts/platform/internals/stacks/2000-01-01-scalingo-14-stack.md, src/_posts/platform/internals/stacks/2000-01-01-scalingo-18-stack.md
scalingo-18 is deprecated, customers have been contacted multiple times about this. We forgot to update a bunch of doc page to reflect this.
=> docs: scalingo-18 deprecation

src/_posts/languages/php/2000-01-01-start.md, src/changelog/buildpacks/_posts/2023-05-31-php-composer-2.5.7.md
Done for:
- `scalingo-20`: https://semver.scalingo.com/composer-scalingo-20/resolve/2.x
- `scalingo-22`: https://semver.scalingo.com/composer-scalingo-22/resolve/2.x
Files have been uploaded to ObjectStorage.
Fixes https://github.com/Scalingo/php-buildpack/issues/328
=> chore(php-buildpack): upgrade Composer to 2.5.7

src/_posts/platform/app/2000-01-01-crash.md
This is a complete rewrite of the "Application Crash" documentation page: the content has been completed, reorganized, rephrased, ... I tried to keep it precise, concise and consistent.
IMHO this was required (the last update dated back to 2016!)
Despite my efforts, there are likely (unwanted) errors, vocabulary mistakes, and such. Please read it carefully and don't hesitate to correct things :)
It also leads to some questions and possible adjustments, hence the PR being in draft mode.
I put these in comments below, so we can handle them separately and provide fixes along the way.
=> fix: rewrite the Application Crash doc

src/_posts/languages/php/2000-01-01-start.md, src/changelog/buildpacks/_posts/2023-06-08-php-default-version-8.1.md
Following https://github.com/Scalingo/semver.io/pull/64
Fixes https://github.com/Scalingo/php-buildpack/issues/330
=> fix/php buildpack/330/set default php version to 8.1

src/_posts/languages/php/2000-01-01-dependencies.md, src/changelog/buildpacks/_posts/2023-06-13-php-composer-2.5.8.md
Done for:
- `scalingo-20`: https://semver.scalingo.com/composer-scalingo-20/resolve/2.x
- `scalingo-22`: https://semver.scalingo.com/composer-scalingo-22/resolve/2.x
Files have been uploaded to ObjectStorage.
Fixes https://github.com/Scalingo/php-buildpack/issues/333
=> chore(php-buildpack): upgrade Composer to 2.5.8

src/changelog/buildpacks/_posts/2023-06-28-nodejs-1.20.1.md
Related to https://github.com/Scalingo/nodejs-buildpack/issues/76
=> fix(changelog): update nodejs buildpack that add support of nodejs 16.20.1

src/_posts/databases/redis/2000-01-01-data-import.md
According to the documentation here:
https://developer.redis.com/riot/#_replicate
The first URL is the source, the second the target.
=> Replicate from source to target

src/_posts/languages/python/django/2000-01-01-start.md
Previous version had deprecated dependencies, as pointed out by @stephane in #2069.
Fixes #2069
=> fix(django): update instructions to get started

src/_posts/languages/go/2000-01-01-start.md, src/changelog/buildpacks/_posts/2023-08-29-go-1.21.0.md
Related to https://github.com/Scalingo/go-buildpack/pull/30
Fixes https://github.com/Scalingo/go-buildpack/issues/29
=> fix(go-buildpack): release of go 1.21.0

src/_posts/platform/app/2000-01-01-datadog.md
A customer got confused and didn't noticed it's needed to also add the language buildpack. I think the page was slightly unclear about that.
=> docs(datadog): give an example of .buildpacks content

src/_posts/addons/scalingo-openvpn/2000-01-01-start.md, src/_posts/addons/scalingo-vpn-ipsec/2000-01-01-start.md
Here is how the block looks:
Fix #1662
=> docs: VPN addons are only for runtime

src/_posts/languages/php/2000-01-01-start.md
This is the documentation update for the following php-buildpack pull request: https://github.com/Scalingo/php-buildpack/pull/351
=> fix(php,datadog): Use the new Datadog installer

src/changelog/buildpacks/_posts/2023-10-30-ruby.md
Fix https://github.com/Scalingo/ruby-buildpack/issues/52
=> chore(ruby-buildpack): sync with upstream v260

src/changelog/buildpacks/_posts/2023-10-30-nodejs-18.18.2-20.9.0-21.1.0.md
Fix https://github.com/Scalingo/nodejs-buildpack/issues/94
=> chore(nodejs-buildpack): sync with upstream v227

src/_includes/organisms/head.html
https://github.com/Scalingo/documentation/issues/2353
Tracker is directly added with the data-domain `scalingo.com` embed.
As, as far I am aware
- we do not having staging env for the docs
- plausible script will auto disable itself when on localhost
=> feat(analytics) Add plausible tracker

src/_includes/organisms/head.html
Adding a custom `app` event in order to be abe to segregate by `app` in the plausible project
https://github.com/Scalingo/documentation/issues/2353
=> feat(analytics) Add plausible tracker, adding a custom `app` event

src/_posts/platform/app/2000-01-01-cors.md
In this doc, it was unclear if Scalingo inject or modify the CORS header. It was confusing customers. So I added a precision to say that no
=> Precision on cors actions by scalingo

src/changelog/buildpacks/_posts/2023-12-11-php-composer-2.6.6.md
Packages have been generated and uploaded on ObjectStorage:
- `scalingo-20`: https://semver.scalingo.com/composer-scalingo-20/versions
- `scalingo-22`: https://semver.scalingo.com/composer-scalingo-22/versions
Fix https://github.com/Scalingo/php-buildpack/issues/383
=> chore(changelog): update composer 2.6.5 to 2.6.6

src/_posts/languages/ruby/2000-01-01-sidekiq.md
Without this, when the application starts, it crashes with the following error:
```
ERROR: Your Redis configuration uses the namespace 'sidekiq-staging' but the redis-namespace gem is not included in the Gemfile.Add the gem to your Gemfile to continue using a namespace. Otherwise, remove the namespace parameter.
```
=> fix(sidekiq): add missing `redis-namespace` gem

src/_posts/platform/app/2000-01-01-postdeploy-hook.md
After reading today the context, I think the doc is actually pretty good on the problematic point. And all the "initializer" part is really Ruby-specific. I don't think it's worth adding something in our doc about that.
Fix #1732
=> docs(postdeploy): insist app boot should not rely on database

src/_posts/platform/getting-started/2000-01-01-getting-started-with-wordpress.md
- Resource can be an array, avoiding duplicate rules.
- Added instructions on bucket policy, as by default, every object is not public, even is the bucket is.
=> Update S3 instructions for WP

src/_posts/platform/deployment/2000-01-01-deploy-java-jar-war.md, src/changelog/buildpacks/_posts/2024-01-02-java-tomcat-webapp-runner-10.1.16.0.md, src/changelog/buildpacks/_posts/2024-01-03-java-tomcat-webapp-runner-10.1.16.0.md
Related to https://github.com/Scalingo/java-war-buildpack/issues/21 and https://github.com/Scalingo/java-war-buildpack/pull/22
=> feat(java-war-buildpack): release of webapp-runner 10.1.16.0

src/_posts/languages/php/2000-01-01-start.md
Frameworks list has been updated after conducting some tests.
*Legacy* apps are now called *Classic*, to keep homogeneity with the buildpack terminology.
Also rephrase a few sentences.
Fix #2378
=> chore(PHP): update PHP start page

src/_posts/languages/python/2000-01-01-start.md, src/_posts/languages/ruby/2000-01-01-start.md, src/changelog/buildpacks/_posts/2024-03-28-nodejs-18.20.0-20.12.0.md, src/changelog/buildpacks/_posts/2024-03-28-php-mongodb-ext-1.18.0.md, src/changelog/buildpacks/_posts/2024-03-28-python-3.8.19-3.9.19-3.10.14.md, src/changelog/buildpacks/_posts/2024-03-28-ruby-3.2.3.md
For the MongoDB PHP extension, files have been generated for:
- `scalingo-20`: PHP `7.4`, `8.0`, `8.1`, `8.2` and `8.3`
- `scalingo-22`: PHP `8.1`, `8.2` and `8.3`
Files have been uploaded to ObjectStorage.
Fix https://github.com/Scalingo/php-buildpack/issues/416
Fix https://github.com/Scalingo/nodejs-buildpack/issues/104
Fix https://github.com/Scalingo/ruby-buildpack/issues/61
Fix https://github.com/Scalingo/python-buildpack/issues/95
=> chore(changelog): update doc

src/_posts/platform/app/2000-01-01-log-drain.md
The url to get an API token from Datadog is invalid
=> Update url to get an API token from Datadog

src/_includes/database_postgresql_extensions.md, src/_posts/databases/postgresql/2000-01-01-overview.md, src/changelog/databases/_posts/2024-04-24-postgresql-14.11.0-2.md
related to https://github.com/Scalingo/appsdeck-database/issues/2935
=> chore(postgres): Bump timescale to 2.14.2

src/_posts/platform/databases/2000-01-01-duplicate.md
Hi there,
I have been using the example script on this page to copy my database (thanks for providing the script!):
https://doc.scalingo.com/platform/databases/duplicate
Overall the script is fine, but I ran into a small issue: when retrieving the backup filename from the TAR archive, we need the filename part *after* the leading slash (second field) and not the one before (first field). Hence we should use `cut -f 2` instead of `cut -f 1`.
```sh
$ tar --list --file=backup.tar.gz  | tail -n 1 | cut -d "/" -f 2
tar: Removing leading `/' from member names
20240503001956_*****************.pgsql
```
=> fix: Fix database duplicate example script

src/_posts/platform/app/2000-01-01-sticky-sessions.md
Fix minor typo in the title of the [Sticky Sessions](https://doc.scalingo.com/platform/app/sticky-sessions) documentation page.
=> fix(platform): Fix typo

tailwind.config.js
Set h2 to 26px
ticket: https://github.com/Scalingo/documentation/issues/2621
=> feat(css): Update h2 font-size to make documentation more readable

src/_includes/scalingo_20_stack_packages.md, src/_includes/scalingo_22_stack_packages.md, src/changelog/base_image/_posts/2024-06-18-scalingo-20-v13-scalingo-22-v10.md
Images (`scalingo-20:v13`, `scalingo-22:v10`, `scalingo-20-minimal:v12` and `scalingo-22-minimal:v9`) have been built and pushed to the registry.
They also have been successfully tested.
Fix https://github.com/Scalingo/appsdeck-builder/issues/406
=> fix(stacks): release of scalingo-20:v13 and scalingo-22:v10

src/_posts/platform/app/2000-01-01-environment.md
Hello
Suggestion for the docs : looks like `HOST` is not exactly an alias for `APP` but the full qualified domain name.
=> docs(environment): hostname composed of app name and container type

src/_posts/languages/ruby/2000-01-01-start.md
Add section about WEB_CONCURRENCY for ruby. 
FIX #2695
=> Add section about WEB_CONCURRENCY for ruby. FIX#2695

src/_posts/languages/nodejs/2000-01-01-start.md
=> docs(nodejs): fix `devDependencies` installation explanation

src/_posts/languages/ruby/2000-01-01-start.md
=> docs(ruby): typo in 'MAX_THREADS' variable name

src/_posts/languages/php/2000-01-01-dependencies.md, src/_posts/languages/python/2000-01-01-start.md, src/changelog/buildpacks/_posts/2024-09-09-go-unmaintained-depencies-managers-deprecation.md, src/changelog/buildpacks/_posts/2024-09-09-nginx-modsecurity-coreruleset-4.6.0.md, src/changelog/buildpacks/_posts/2024-09-09-nodejs-22.8.0.md, src/changelog/buildpacks/_posts/2024-09-09-php-composer-2.7.9.md, src/changelog/buildpacks/_posts/2024-09-09-python-3.8.20-3.9.20-3.10.15-3.11.10-3.12.6.md
Fix https://github.com/Scalingo/php-buildpack/issues/456
Fix https://github.com/Scalingo/python-buildpack/issues/112
Fix https://github.com/Scalingo/nodejs-buildpack/issues/141
Fix https://github.com/Scalingo/nginx-buildpack/issues/61
Fix https://github.com/Scalingo/go-buildpack/issues/44
For the Composer upgrade, files have been uploaded on ObjectStorage:
- `scalingo-20`: https://semver.scalingo.com/composer-scalingo-20/resolve/2.7.x
- `scalingo-22`: https://semver.scalingo.com/composer-scalingo-22/resolve/2.7.x
- `scalingo-20-minimal`: https://semver.scalingo.com/composer-scalingo-20-minimal/resolve/2.7.x
- `scalingo-22-minimal`: https://semver.scalingo.com/composer-scalingo-22-minimal/resolve/2.7.x
=> chore(changelog): misc. buildpack updates

src/_posts/databases/elasticsearch/2000-01-01-start.md, src/_posts/databases/influxdb/2000-01-01-start.md, src/_posts/databases/mongodb/2000-01-01-compass.md, src/_posts/databases/mongodb/2000-01-01-robo3t.md, src/_posts/databases/mongodb/2000-01-01-start.md, src/_posts/databases/mysql/2000-01-01-connecting.md, src/_posts/databases/mysql/2000-01-01-managing.md, src/_posts/databases/postgresql/2000-01-01-connecting.md, src/_posts/databases/postgresql/2000-01-01-managing.md, src/_posts/databases/redis/2000-01-01-start.md
Specify DB users passwords are between 24 and 64 characters long.
Enforce 64 characters longs DB users passwords in examples.
=> [STORY-648] docs: DB users passwords are between 24 and 64 characters long

src/_posts/platform/deployment/2000-01-01-deploy-java-jar-war.md, src/changelog/buildpacks/_posts/2024-09-20-java-tomcat-webapp-runner-9.0.93.0-10.1.28.0.md, src/changelog/buildpacks/_posts/2024-09-20-nginx-owasp-modsecurity-3.0.13.md, src/changelog/buildpacks/_posts/2024-09-20-php-mongodb-ext-1.19.4.md
- MongoDB packages have been uploaded to ObjectStorage for:
- `scalingo-20`: PHP `7.4`, `8.0`, `8.1`, `8.2` and `8.3`
- `scalingo-22`: PHP `8.1`, `8.2` and `8.3`.
- Java webapp-runner `9.0.93.0` and `10.1.28.0` have been uploaded to ObjectStorage.
- OWASP ModSecurity `3.0.13` packages have been uploaded to ObjectStorage for:
- `scalingo-20`
- `scalingo-22`
Fix https://github.com/Scalingo/php-buildpack/issues/457
Fix https://github.com/Scalingo/java-war-buildpack/issues/40
Fix https://github.com/Scalingo/nginx-buildpack/issues/63
=> chore(php-buildpack,war): misc buildpacks updates

src/changelog/buildpacks/_posts/2024-10-07-nodejs-20.18.0.md, src/changelog/buildpacks/_posts/2024-10-07-php-phpredis-ext-6.1.0.md
phpredis packages have been generated and uploaded to ObjectStorage:
- For `scalingo-20`: PHP `7.4`, `8.0`, `8.1`, `8.2` and `8.3`
- For `scalingo-22`: PHP `8.1`, `8.2` and `8.3`
Fix https://github.com/Scalingo/php-buildpack/issues/467
Fix https://github.com/Scalingo/nodejs-buildpack/issues/145
=> chore(nodejs,php): changelogs

src/_posts/platform/deployment/buildpacks/2000-01-01-nginx.md
This feature does not exist in the Nginx buildpack (https://github.com/search?q=repo%3AScalingo%2Fnginx-buildpack%20NGINX_INCLUDES&type=code). Let's remove this section.
It was added a while back (#758) but lots of things are wrong about this addition. Let's forget about this
=> docs(nginx): remove not implemented feature

src/_posts/platform/databases/2000-01-01-maintenance-windows.md
Add maintenance windows db part
We need to see how we can manage a global database access documentation, as for the moment, I set the link to PG dashboard
=> [STORY-468] feat(db): Add maintenance windows through dashboard

src/_posts/languages/php/2000-01-01-laravel.md
Add instructions to laravel page
Fixes issue #2843
=> fix: How to run `php artisan optimize` using postdeploy hook

redirections.yml, src/_posts/databases/postgresql/2000-01-01-managing.md, src/_posts/databases/postgresql/2000-01-01-upgrading.md
STORY-1091
This PR creates a new page in Database/PostgreSQL describing the different upgrades and information about them. This should ease the communication with customers when we deprecate a PostgreSQL version and "force" them to upgrade.
I hope this will also be helpful for support.
=> feat(postgresql): add Upgrading page for PostgreSQL

src/_posts/databases/mysql/2000-01-01-managing.md
A new subsection "Updating the Default User Password" in "Managing Your Scalingo for MySQL® Addon" page
Fixes #2905
=> fix: MySQL Updating the Default User Password

src/_posts/platform/cli/2000-01-01-features.md
Fix missing `--app my-app` flag with the `backups` command.
=> fix(cli): add missing `--app` flag for backups commands

src/_posts/databases/mongodb/2000-01-01-compass.md
Within db-tunnel, the MongoDB connection configuration Compass requires the field `Authentication Database` to be filled.
As opposed to `Username` and `Password`, the field is not specified, and may takes time to guess it if you're not used 
to (like me).
Fix #2957
=> doc: specify Authentication database among Compass connection fields

src/_posts/platform/internals/stacks/2000-01-01-stacks.md
Replace references to Docker with more generic references to Linux containers.
=> Mention Linux Containers instead of Docker

src/changelog/buildpacks/_posts/2025-01-23-nodejs-18.20.6-20.18.2-22.13.1-23.6.1.md
Fix https://github.com/Scalingo/nodejs-buildpack/issues/164
=> chore: release of Node.js 18.20.1, 20.18.2, 22.13.1 and 23.6.1

src/_posts/languages/python/django/2000-01-01-start.md
Hi there :wave: 
This week it was the first time I deployed a Django app to Scalingo. It works really well! I spotted some quirks in the documentation so here is a PR that fixes them:
- There is a useless section about the `collectstatic` command; maybe the Python buildpack has started handling that part quite recently and the docs hasn't been updated, but clearly now it's useless
- The serving of static files is recommended through `dj-static`, a Django app that's completely unmaintained for a long time; so I replaced it with whitenoise, the new standard on that matter
=> Improve documentation for Django

src/_posts/languages/java/2000-01-01-start.md, src/changelog/buildpacks/_posts/2025-02-05-java-23.0.2-21.0.6-17.0.14-11.0.26-8.0_442.md
Fix https://github.com/Scalingo/buildpack-jvm-common/issues/56
=> chore(java): JDK 1.8.0_442, 11.0.26, 17.0.14, 21.0.6 and 23.0.2

src/_posts/security/procedures/2000-01-01-secnumcloud.md
Update 2000-01-01-secnumcloud.md: EN improvement + ID control step addition Was discussed with support team in November 2024 to make external process clearer.
=> [ICY-468] Update 2000-01-01-secnumcloud.md: EN improvement + ID control step addition

src/_posts/databases/postgresql/2000-01-01-backing-up.md
=> fix(postgresql): fix var name in pg_dump command

assets/style.css
Fix table view on mobile without using 
`<div class="overflow-horizontal-content" markdown="1">`
=> [STORY-1326] fix(css): fix table view on mobile

src/_posts/languages/ruby/2000-01-01-start.md, src/changelog/buildpacks/_posts/2025-03-20-ruby-3.3.7.md
Fix https://github.com/Scalingo/ruby-buildpack/issues/100
=> chore(ruby-buildpack): defaults to Ruby 3.3.7

src/_posts/databases/postgresql/2000-01-01-accessing.md
I think the port has to be placed between `db-tunnel` and the URL.
=> change parameter order on db-tunnel

src/_posts/languages/php/2000-01-01-sending-emails.md
Fixes #1085
This PR adds some basic information about sending emails from PHP, and an example using Brevo.
=> docs(php) - sending emails

src/_posts/platform/getting-started/2000-01-01-getting-started-with-elk.md
This PR fixes the Getting Started tutorial for ELK and adds the command to check out the correct branch.
=> Fix: ElasticSearch tutorial

src/_posts/platform/app/2000-01-01-log-drain.md
For a full betterstack support, the host is also required on top of the token.
WIth https://github.com/Scalingo/logs-service/issues/540.
=> Update Betterstack log-drain documentation

src/_posts/languages/ruby/2000-01-01-start.md
- Update fallback value for MAX_THREADS (Rails now recommends 3 instead of 5)
- Clarify that MAX_THREADS is not automatically set, but WEB_CONCURRENCY is, and how to override it.
=> Improve ruby documentation

src/_posts/databases/opensearch/about/2000-01-01-overview.md, src/_posts/databases/opensearch/getting-started/2000-01-01-accessing.md, src/changelog/databases/_posts/2025-09-05-opensearch-2.19.3-1.md
!! NO MERGE BEFORE OPENSEARCH VERSION 2.19.3 BUMP IN APPSDECK-DATABASE !!
Fix [#3624](https://github.com/Scalingo/appsdeck-database/issues/3624)
=> Update doc for new OpenSearch version 2.19.3-1

src/changelog/cli/_posts/2025-09-11-1.39.0.md, src/changelog/cli/_posts/2025-09-24-1.40.0.md, src/changelog/sdk/_posts/2025-09-23-go-scalingo-v8.6.0.md, src/changelog/sdk/_posts/2025-09-24-go-scalingo-v8.7.0.md, src/changelog/tools/_posts/2025-09-24-terraform-provider-scalingo-2.6.0.md
I also created the 1.39 release not for the CLI, which was missing.
=> Create latest releases for CLI, go-scalingo and terraform-provider-scalingo

src/_posts/security/bulletins/2025-10-07-SSB-2025-001.md
From recent detection, CVE-2025-49844
Tracked in this SECINC issue: [125](https://scalingo.atlassian.net/browse/SECINC-125)
&
[VUL-366](https://scalingo.atlassian.net/browse/VUL-366)
All remediations handled here:
[#3687 bump(redis) Version 6.2.20 and 7.2.11 to fix CVE‑2025‑49844](https://github.com/Scalingo/appsdeck-database/pull/3687)
[#3377 changelog(databases) 2025-10-07-redis.7.2.11-1.md](https://github.com/Scalingo/documentation/pull/3377)
[VUL-366]: https://scalingo.atlassian.net/browse/VUL-366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SECINC-125] SSB-2025-001
