_posts/databases/2015-09-30-dump-restore-mongodb.md, _posts/databases/2015-10-01-dump-restore-mysql.md
+ Dump and restore a Mysql database
=> Add more logic to examples, variable names, various fixes

_posts/getting-started/2000-01-01-migrate-from-shelly-cloud.md
=> Shelly cloud migration

_posts/cli/2015-09-18-command-line-tool.md, _posts/ssh/2015-04-04-setup-ssh-windows.md
* Add installation steps Linux+Win to CLI page #61
* Setup ssh for windows
=> CLI Installation + Ssh setup windows

_includes/head.html
Add of a single quote to validate fb image
=> fixed og-image url not quote-terminated

_sass/search.sass
Also add a bigger input font-size
=> Fixed css typo and search input compatiblity with OSX and firefox

_posts/databases/2015-06-24-access-database.md, _posts/deployment/2015-12-16-one-click-deploy.md
To merge when https://github.com/Scalingo/developers.scalingo.com/pull/26 is merged
=> Link to the scalingo.json schema

_posts/internals/buildpacks/2015-01-04-buildpacks.md, _posts/languages/java/2016-10-26-gradle.md
Related to Scalingo/appsdeck-builder#67
=> Add Gradle buildpack documentation

_posts/languages/php/2014-07-02-php.md
added the missing [  ] from the example
=> Fixed the .extra.paas.php-config example

_posts/2000-01-01-git-submodule.md
=> Documentation about git submodule

_posts/deployment/2017-08-03-deploy-with-git.md
=> Add page Deploy with git

_posts/internals/buildpacks/2015-01-04-custom-buildpacks.md, _posts/internals/buildpacks/2015-09-28-multi-buildpack.md
=> Add order buildpack section fix #158

_posts/databases/2000-01-01-scalingo-elasticsearch-addon.md, _posts/databases/2000-01-01-scalingo-influxdb-addon.md, _posts/databases/2000-01-01-scalingo-mongodb-addon.md, _posts/databases/2000-01-01-scalingo-mysql-addon.md, _posts/databases/2000-01-01-scalingo-postgresql-addon.md, _posts/databases/2000-01-01-scalingo-redis-addon.md
Related to Scalingo/appsdeck-database#396
=> Add doc about TLS in DB

_includes/info_tutorial_requirements.md
=> Fix typo in tutorial requirements

_posts/addons/2017-10-23-tcp-addon.md
=> Add an article on the new TCP addon

_posts/addons/2017-10-23-tcp-addon.md
=> Add tcp addon limitations

_posts/internals/2000-01-01-your-account.md, _posts/internals/2017-08-08-your-account.md, _posts/languages/go/2000-01-01-godep.md, css/main.sass
=> Write page Your Account

_config.yml, config.ru
=> Use pretty permalink + redirect .html to /

_posts/integrations/2000-01-01-cloudflare-scalingo-app.md, css/main.sass
Fixes #209
[![image](https://screenshotscdn.firefoxusercontent.com/images/b4c0be2f-28c1-43b6-95de-fc6e2d539e9a.png)](https://screenshotscdn.firefoxusercontent.com/images/b4c0be2f-28c1-43b6-95de-fc6e2d539e9a.png)
=> Add article about cloudflare and scalingo apps

_posts/databases/2000-01-01-redis-data-import.md
=> Import data from an external Redis Database

_posts/internals/2000-01-01-scalingo-builder-base-docker-image.md, _posts/internals/buildpacks/2000-01-01-apt-buildpack.md, _posts/internals/buildpacks/2000-01-01-cairo-buildpack.md, _posts/internals/buildpacks/2000-01-01-graphicsmagick-buildpack.md, _posts/internals/buildpacks/2015-01-04-buildpacks.md, _posts/internals/buildpacks/2015-09-28-ffmpeg-buildpack.md, _posts/internals/buildpacks/2015-09-28-multi-buildpack.md
=> Add APT buildpack documentation

yarn.lock
=> updated scalingo styles 

_posts/platform/app/2000-01-01-domain.md
=> Add section about canonical domain

README.md, _posts/platform/app/2000-01-01-custom-error-page.md
=> page explaining how to set custom error/maintenance page

_posts/addons/scalingo-mysql/2000-01-01-start.md
=> Add a note about phpMyAdmin

_posts/platform/app/2000-01-01-tasks.md
=> Add a section for --detached option

_posts/platform/deployment/buildpacks/2000-01-01-ssh-key.md
=> Page about the SSH private key buildpack

_posts/platform/deployment/buildpacks/2000-01-01-locale.md
=> Page about the locale buildpack

_posts/addons/scalingo-mysql/2000-01-01-start.md, _posts/platform/databases/2000-01-01-adminer.md
=> Add page about Adminer

changelog/tools/_posts/2018-04-20-adminer-4.6.2.md
=> Changelog for Adminer 4.6.2

_posts/platform/app/2000-01-01-cors.md
=> Add doc about CORS

_posts/platform/app/2000-01-01-cloudflare-scalingo-app.md, _posts/platform/internals/2000-01-01-network.md
=> Add page about Scalingo network

_posts/addons/scalingo-mongodb/2000-01-01-start.md
=> Add information about upgrading a replica set

_posts/platform/app/2000-01-01-logs.md, _posts/platform/cli/2000-01-01-features.md, _posts/platform/internals/2000-01-01-base-docker-image.md
https://documentation-service-pr346.scalingo.io/platform/app/logs
Fix #131
=> Add doc about logs and timezone

_posts/platform/internals/2000-01-01-base-docker-image.md
=> Fixing a typo

_posts/platform/app/2000-01-01-postdeploy-hook.md, _posts/platform/app/2000-01-01-procfile.md
Related to Scalingo/developers.scalingo.com#30
https://documentation-service-pr354.scalingo.io/platform/app/procfile#postdeploy-hook
=> link to post-deploy hook from Procfile page

_posts/addons/scalingo-mongodb/2000-01-01-dump-restore.md, _posts/platform/databases/2000-01-01-access.md
Fix #366
https://documentation-service-pr367.scalingo.io/addons/scalingo-mongodb/dump-restore#setup-the-tunnel
https://documentation-service-pr367.scalingo.io/platform/databases/access#build-the-tunnel
=> Add a warning about replica set and DB tunnel

_posts/platform/app/2000-01-01-datadog-scalingo.md
https://documentation-service-pr369.scalingo.io/platform/app/datadog-scalingo
Fix #317
=> Datadog configuration on Scalingo

_posts/platform/internals/2000-01-01-router-error-codes.md, _posts/platform/internals/2000-01-01-routing.md
https://documentation-service-pr372.scalingo.io/platform/internals/router-error-codes
Fix #360
=> Better explain HTTP 504 in router error codes page

_posts/platform/app/2000-01-01-logs.md
https://documentation-service-pr374.scalingo.io/platform/app/logs
Fix #361
=> Explain when logs are archived

_posts/platform/app/2000-01-01-tasks.md
=> Document dbclient-fetcher

_posts/languages/python/2000-01-01-start.md, _posts/platform/app/2000-01-01-postdeploy-hook.md
=> Python specific hooks

_posts/platform/app/2000-01-01-log-drain.md
https://documentation-service-pr370.scalingo.io/platform/app/log-drain
@Soulou Do you want to enforce an environment variable name for the token, to prepare the release of the non-beta feature? Or it will not be about an environment variable name?
Fix #356
=> Introduce logs drain as a beta feature

_posts/databases/redis/2000-01-01-start.md
I rephrased the paragraph talking about these timeouts. But I don't really see how we can organize this page so that customers do not miss it... maybe add bold to a few words?..
Fix #385
=> Rephrase Redis idle timeout

_posts/platform/internals/2000-01-01-network.md
https://documentation-service-pr402.scalingo.io/platform/internals/network#ipv6
Fix #389
=> Mention that we do not support yet IPv6

_posts/platform/deployment/buildpacks/2000-01-01-custom.md
https://documentation-service-pr400.scalingo.io/platform/deployment/buildpacks/custom
Fix #391
=> Use a branch of a custom buildpack

_includes/database_backups.md, _posts/databases/mongodb/2000-01-01-start.md, _posts/languages/java/2000-01-01-gradle.md, _posts/languages/php/2000-01-01-wordpress.md, _posts/platform/databases/2000-01-01-restore-backup.md, _posts/platform/deployment/buildpacks/2000-01-01-ffmpeg.md, _posts/platform/deployment/buildpacks/2000-01-01-multi.md, _posts/platform/getting-started/2000-01-01-common-deployment-errors.md, _posts/platform/internals/2000-01-01-base-docker-image.md, app/javascript/css/application.scss
https://documentation-service-pr398.scalingo.io/platform/databases/restore-backup
Fix #392
=> Add a page to explain how to restore a database backup

_posts/languages/php/2000-01-01-start.md
https://documentation-service-pr399.scalingo.io/languages/php/start
Fix #397
=> Add CodeIgniter to the list of supported framework

_posts/platform/app/2000-01-01-app-manifest.md, _posts/platform/app/2000-01-01-review-apps.md
https://documentation-service-pr409.scalingo.io/platform/app/review-apps
=> Explicitely describe how to execute tasks at the first deployment of a review app and at each deployment

_posts/databases/redis/2000-01-01-start.md
https://documentation-service-pr403.scalingo.io/databases/redis/start#persistence-mode
Fix #388
=> Redis persistence configuration

_posts/platform/internals/2000-01-01-container-sizes.md, _posts/platform/internals/2000-01-01-recovery-management.md, _posts/platform/internals/2000-01-01-router-error-codes.md
https://documentation-service-pr396.scalingo.io/platform/internals/container-sizes
A couple of questions for @Soulou:
- What is the difference PIDs limit and ulimit nproc?
- Should we mention the bandwidth limit?
Fix #382
Fix #378
=> Add containers limits

Gemfile.lock, _posts/platform/deployment/2000-01-01-cache.md
=> Add deployment cache doc

_posts/platform/deployment/2000-01-01-limits.md
=> Article about limits in the deployment environment

_config.yml
=> Add sample Laravel Mix

_includes/dbclient_fetcher.md, _posts/platform/app/2000-01-01-tasks.md, _posts/platform/databases/2000-01-01-access.md
https://documentation-service-pr413.scalingo.io/platform/databases/access#manually-install-the-databases-cli-in-one-off
Fix #408
=> Improve dbclient-fetcher doc

_config.yml
@yannski I wanted to add the Rails logo but I don't know how you do it in the samples list to generate these logos
Related to #319
=> Add sample Ruby on Rails

Gemfile.lock, _posts/platform/app/2000-01-01-domain.md, _posts/platform/app/2000-01-01-ssl.md
=> Add documentation to create Let's Encrypt wildcard certificates

_posts/platform/internals/2000-01-01-container-sizes.md
https://documentation-service-pr427.scalingo.io/platform/internals/container-sizes#container-limits
Fix #420
=> More detail for the PID limits

changelog/cli/_posts/2018-03-29-1.8.0.markdown, changelog/cli/_posts/2018-07-31-1.9.0.md
https://documentation-service-pr425.scalingo.io/changelog
Fix #423
=> Changelog entry for CLI 1.9.0

_posts/languages/python/2000-01-01-celery-flask.md
=> Mention Python in the Celery/Flask get started

_posts/platform/internals/2000-01-01-routing.md
https://documentation-service-pr376.scalingo.io/platform/internals/routing#headers
Fix #365
=> X-Scalingo-Error header

_posts/platform/getting-started/2000-01-01-getting-started-with-elk.md
=> Add ELK getting started

_posts/languages/nodejs/2000-01-01-websocket-web-same-port.md
=> Add article for WebSocket and HTTP server listening on the same port

_posts/languages/ruby/2000-01-01-getting-started-with-ruby.md, _posts/languages/ruby/2018-02-23-getting-started-with-ruby.md, _posts/platform/app/2000-01-01-postdeploy-hook.md
=> Add ruby getting started

_posts/languages/ruby/2000-01-01-private-gem-from-github-on-scalingo.md
=> Mention bundler way of using private repo

_posts/platform/app/2000-01-01-autoscaler.md, _posts/platform/app/2000-01-01-scaling.md
https://documentation-service-pr226.scalingo.io/platform/app/autoscaler
Fix #219
=> Autoscaling page

_posts/getting-started/php/2018-02-23-getting-started-with-php.md, _posts/languages/crystal/2000-01-01-start.md, _posts/languages/php/2000-01-01-tutorial.md, _posts/languages/python/2000-01-01-celery-flask.md, _posts/languages/scala/2000-01-01-start.md, _posts/platform/app/2000-01-01-lifecycle-management.md, _posts/platform/getting-started/2000-01-01-first-steps.md
=> Add a PHP Getting Started page

_posts/databases/mysql/2000-01-01-start.md
https://documentation-service-pr444.scalingo.io/databases/mysql/start#web-administration-tools
Fix #442
=> Add Adminer along with phpMyAdmin on MySQL page

changelog/tools/_posts/2018-11-26-adminer-4.7.0.md
https://documentation-service-pr461.scalingo.io/changelog
=> Adminer update to 4.7.0

changelog/tools/_posts/2018-12-12-phpmyadmin-4.8.4.md
https://documentation-service-pr473.scalingo.io/changelog
=> [Changelog] Update phpMyAdmin to 4.8.4

_posts/languages/2000-01-01-nodejs.md, _posts/languages/nodejs/2000-01-01-tutorial.md, _posts/platform/app/2000-01-01-force-https.md, _posts/platform/deployment/2000-01-01-deployment-process.md
=> Replace forever with nodemon

changelog/databases/_posts/2019-01-07-elasticsearch-5.5.3-7.markdown
It has been a long time since we announced an ES new version
=> ES version 5.5.3-7

_posts/languages/php/2019-02-07-php-nodejs.md, _posts/platform/deployment/buildpacks/2000-01-01-multi.md
Fix #488
https://documentation-service-pr492.scalingo.io/languages/php/php-nodejs
=> Add a page to explain the setup of a PHP app using Node.js

_posts/languages/python/2000-01-01-nltk.md
Fix #486 
https://documentation-service-pr494.scalingo.io/languages/python/nltk
=> Document the nltk feature of the Python buildpack

_posts/databases/elasticsearch/2000-01-01-start.md, _posts/databases/influxdb/2000-01-01-start.md, _posts/databases/mongodb/2000-01-01-start.md, _posts/databases/mysql/2000-01-01-start.md, _posts/databases/postgresql/2000-01-01-start.md, _posts/databases/redis/2000-01-01-start.md
https://documentation-service-pr457.scalingo.io/databases/elasticsearch/start#elasticsearch-cluster-setup
We still need to:
Related to Scalingo/appsdeck-database#340
=> Explain ES cluster

_posts/platform/cli/2000-01-01-features.md
=> [CLI] Login with GitHub account

_posts/platform/app/2000-01-01-log-drain.md
=> How to format env variable

_posts/platform/app/2000-01-01-postdeploy-hook.md
=> Instruct where to build assets

_posts/languages/php/2000-01-01-laravel.md
=> [Laravel] How to use queues

_includes/info_command_line_tool.md, _posts/languages/meteorjs/2000-01-01-npm.md, _posts/languages/meteorjs/2000-01-01-start.md, _posts/platform/databases/2000-01-01-access.md
=> [Meteor] Set custom timezone

_posts/languages/nodejs/2000-01-01-start.md, _posts/platform/app/2000-01-01-static-files-hosting.md
=> [React Native] Deplloy React Native app on Scalingo

_posts/addons/scalingo-docker-image/2000-01-01-start.md
=> [Docker Addon] Add username of Docker image

_posts/languages/php/2000-01-01-start.md
=> [PHP] Default configuration

_posts/platform/app/2000-01-01-ssl.md
=> DNS CAA configuration for Let's Encrypt

app/javascript/css/application.scss
=> Fix padding

_posts/platform/deployment/2000-01-01-deploy-with-git.md
=> [Git] Deploy a specific commit ID

_posts/languages/php/2000-01-01-wordpress.md
=> [WordPress] Use Bedrock!

_posts/languages/java/2000-01-01-start.md
=> Add custom CA to java app

_posts/languages/scala/2000-01-01-start.md
=> Add documentation about Scala app packaging if project is misconfigured

_posts/platform/app/2000-01-01-domain.md
=> Explain Let's Encrypt backoff and how to trigger a check immediately after DNS update

_posts/languages/elixir/2000-01-01-start.md
=> [Elixir] Add introduction

_posts/languages/go/2000-01-01-start.md
=> [Go] Add compile hooks

_posts/databases/postgresql/2000-01-01-start.md
=> Mention PostgreSQL users rights

_posts/platform/deployment/buildpacks/2000-01-01-custom.md
https://documentation-service-pr533.scalingo.io/platform/deployment/buildpacks/custom
Fix #522
=> Document how to develop a custom buildpack

_posts/databases/redis/2000-01-01-data-import.md, _posts/languages/ruby/rails/2000-01-01-redis-cache.md, _posts/languages/ruby/rails/2000-01-01-start.md
https://documentation-service-pr371.scalingo.io/languages/ruby/rails/redis-cache
Fix #357
=> Using redis as cache engine for Rails

_posts/platform/app/2000-01-01-cloudflare-scalingo-app.md
=> Cloudflare full encryption mode wil work out of the box

_includes/nginx_includes.md, _posts/languages/php/2000-01-01-symfony.md, _posts/languages/php/2019-02-08-php-session-redis.md
https://documentation-service-pr496.scalingo.io/languages/php/php-session-redis
Fix #476
=> How to use Redis for PHP session

_posts/databases/mysql/2000-01-01-start.md
=> Add MySQL client certificate

_posts/platform/app/2000-01-01-alerts.md
Related to Scalingo/scalingo-alerter-service#97
=> Add doc about duration_before_trigger attribute

_config.yml, _posts/languages/java/2000-01-01-start.md
Fix #524
I will update the sample to adopt the template we have on all of the samples.
=> Mention the JVM programming languages, including Kotlin

_posts/databases/elasticsearch/2000-01-01-start.md, _posts/databases/redis/2000-01-01-start.md
=> Documentation about Redis HA

changelog/databases/_posts/2019-04-12-redis-4.0.14.markdown
=> [Changelog] Redis 4.0.14 with HA

_posts/platform/app/2000-01-01-app-manifest.md
Addon plans have changed.
I've added the reference to the CLI commands to list the current plans.
=> Changed addons' plan names

_posts/platform/app/2000-01-01-alerts.md
=> Simplify text for explanation of alert duration

_posts/platform/databases/2000-01-01-intro.md
=> Explain how we handle encryption at rest

_posts/platform/app/2000-01-01-environment.md
Fix #548
https://documentation-service-pr564.scalingo.io/platform/app/environment
=> Document SCALINGO_USER_ID one-off env variable

_posts/platform/app/2000-01-01-slugignore.md
Fix #547
https://documentation-service-pr563.scalingo.io/platform/app/slugignore
=> Slugignore example for Rails with Webpack

_posts/languages/php/2000-01-01-symfony.md
Fix #558
https://documentation-service-pr566.scalingo.io/languages/php/symfony
=> Explain Doctrine database migration

_config.yml
https://documentation-service-pr594.scalingo.io/samples
=> Correctly display InfluxDB logo

README.md, _config.yml
Fix #544
https://documentation-service-pr593.scalingo.io/samples
=> Add Kotlin and PHP/Phalcon samples

_posts/languages/php/2000-01-01-blackfire.md
=> How to use Blackfire on Scalingo

_posts/platform/internals/2000-01-01-network.md
=> Make the outgoing IP easier to find through search bar

_posts/platform/internals/2000-01-01-multi-regions.md
=> Add a page about multi regions

_posts/platform/app/2000-01-01-autoscaler.md
=> Better explanation on how to get the target

_posts/platform/cli/2000-01-01-features.md
=> CLI support HTTP proxy configuration

_posts/platform/internals/2000-01-01-regions.md
=> Documentation on how to migrate an application from one region to another

_posts/platform/app/2000-01-01-domain.md, _posts/platform/internals/2000-01-01-network.md
=> Add 3DS Outscale Paris network configuration

_includes/ssh_urls.md, _posts/databases/mongodb/2000-01-01-compass.md, _posts/databases/mongodb/2000-01-01-robo3t.md, _posts/languages/python/django/2000-01-01-start.md, _posts/platform/app/2000-01-01-child-apps.md, _posts/platform/databases/2000-01-01-access.md, _posts/platform/deployment/2000-01-01-deploy-scalingo-from-bitbucket.md, _posts/platform/deployment/2000-01-01-deploy-scalingo-from-codeship.md, _posts/platform/deployment/2000-01-01-deploy-scalingo-from-semaphore-ci.md, _posts/platform/deployment/2000-01-01-deploy-with-git.md
=> [regions] Update SSH hostname and port and the Git remote URL with new region

_posts/platform/deployment/2000-01-01-deploy-with-github.md
=> Give permission to Scalingo to access your org repositories

_posts/platform/internals/2000-01-01-routing.md
=> Explain quarantine mode for user's containers

_posts/languages/nodejs/2000-01-01-start.md
=> Private dependency with npm

_includes/database_backups.md, _posts/databases/postgresql/2000-01-01-start.md
Related to Scalingo/appsdeck-database#1152
=> Updated deletion strategy for all database types backups

changelog/cli/_posts/2019-07-29-1-15-1.md
=> [changelog] CLI 1.15.1

_posts/languages/go/2000-01-01-start.md
=> Page about using private git repo in a go deployment

_posts/languages/php/2019-02-07-php-nodejs.md, _posts/platform/app/2000-01-01-slugignore.md
=> Add sample of slugignore for PHP+Node.js apps

_posts/languages/meteorjs/2000-01-01-start.md, _posts/languages/php/2000-01-01-basic-auth.md
=> Add instruction to setup basic auth on MeteorJS

_posts/databases/mongodb/2000-01-01-compass.md
=> Instructions if plan with single node

_posts/databases/mysql/2000-01-01-start.md, _posts/databases/mysql/2000-01-01-workbench.md
=> How to connect with MySQL Workbench

_posts/platform/deployment/2000-01-01-stacks.md
=> Add doc about stacks

_posts/databases/mysql/2000-01-01-start.md
=> Add link to Adminer and phpMyAdmin on osc-fr1

_posts/languages/php/2000-01-01-basic-auth.md
=> Add example of basic auth depending on the hostname

_posts/platform/cli/2000-01-01-features.md
=> Mention regions in CLI page

_posts/databases/mysql/2000-01-01-start.md
=> Explain MySQL URL format

_posts/platform/internals/2000-01-01-base-docker-image.md
=> Mentionned maximum build time 

_posts/platform/deployment/2000-01-01-deploy-scalingo-from-circle-ci.md
Sorry, not tested, but should work.
=> Update docs for CircleCI 2.0.

_posts/languages/clojure/2000-01-01-start.md, _posts/languages/crystal/2000-01-01-start.md, _posts/languages/meteorjs/2000-01-01-telescope.md, _posts/languages/meteorjs/2000-01-01-tutorial.md, _posts/languages/nodejs/2000-01-01-tutorial.md, _posts/languages/php/2000-01-01-codeigniter.md, _posts/languages/php/2000-01-01-start.md, _posts/languages/php/2000-01-01-tutorial.md, _posts/languages/php/2000-01-01-wordpress.md, _posts/languages/python/django/2000-01-01-start.md, _posts/languages/ruby/2000-01-01-getting-started-with-ruby.md, _posts/languages/ruby/rails/2000-01-01-start.md, _posts/languages/scala/scalatra/2000-01-01-start.md, _posts/platform/app/2000-01-01-child-apps.md, _posts/platform/app/2000-01-01-cloudflare-scalingo-app.md, _posts/platform/app/2000-01-01-cors.md, _posts/platform/app/2000-01-01-domain.md, _posts/platform/app/2000-01-01-force-https.md, _posts/platform/app/2000-01-01-integrate-parse-ios.md, _posts/platform/app/2000-01-01-log-drain.md, _posts/platform/app/2000-01-01-ssl.md, _posts/platform/app/2000-01-01-sticky-sessions.md, _posts/platform/deployment/2000-01-01-deploy-java-jar-war.md, _posts/platform/getting-started/2000-01-01-getting-started-with-elk.md
=> App FQDN depends on the region

_posts/platform/app/2000-01-01-log-drain.md
As explained here: https://app.intercom.io/a/apps/w4oogu7s/inbox/inbox/search/conversations/16326845530?assigneeIdentifier=all&q=papertrail
=> [Log Drain] We also support Papertrail

changelog/databases/_posts/2019-11-07-mongo-3.6.15-1.markdown
Related to https://github.com/Scalingo/appsdeck-database/pull/1342
=> [changelog] MongoDB 3.6.15-1

_posts/platform/app/2000-01-01-cloudflare-scalingo-app.md
=> Add a 'End-to-end HTTPS' section

_posts/addons/lab/scalingo-object-storage/2000-01-01-start.md, _posts/addons/lab/scalingo-shared-filesystem/2000-01-01-start.md
=> Add 'beta' warning at the begining of object storage and filesystem addon

_posts/platform/internals/2000-01-01-container-sizes.md
=> All containers have access to all CPU cores

_posts/languages/meteorjs/2000-01-01-start.md, _posts/platform/internals/2000-01-01-base-docker-image.md
=> Add a word about how to set the application timezone

_posts/platform/app/2000-01-01-log-drain.md
=> Add instruction to get Datadog, Logentries, OVH Graylog and Papertrail

_posts/languages/php/2000-01-01-symfony.md
=> Instruct Symfony that app is behind a reverse proxy

_posts/platform/app/2000-01-01-log-drain.md
Related to https://github.com/Scalingo/logs-service/issues/201
=> Add Datadog region support

_posts/platform/app/2000-01-01-force-https.md
=> Explain how to activate Force HTTPS on a  Scalingo app

_posts/platform/app/2000-01-01-review-apps.md
=> [Review App] Protect access with basic auth

_posts/databases/postgresql/2000-01-01-extensions.md
=> Add a warning to explain that PostGIS requires at least Starter 512M

_posts/databases/postgresql/2000-01-01-dump-restore.md
=> Dump from one-off needs to call dbclient-fetcher

_posts/platform/deployment/buildpacks/2000-01-01-nginx.md
=> NGINX_INCLUDES documentation

_posts/platform/app/2000-01-01-secret-file-in-app.md
=> Page about how to get access to private file in app

_posts/languages/java/2000-01-01-start.md
Fix #701
From https://github.com/Scalingo/buildpack-jvm-common/blob/0a7f5998149118c55389993e0c55c6fec14c3f88/opt/jvmcommon.sh#L7-L29
=> Add default Xmx JVM conf

_config.yml
https://sample-python-django.osc-fr1.scalingo.io/
Fix https://github.com/Scalingo/python-buildpack/issues/8
=> Add Django sample

_posts/platform/internals/2000-01-01-base-docker-image.md
=> we're now based on Ubuntu 18.04

_posts/platform/app/2000-01-01-procfile.md
=> added a conditional Procfile entry sample

_posts/languages/ruby/2000-01-01-bundler-configuration.md, redirections.yml
The page was referenced in the buildpack but inexistant
=> Add ruby page about bundler configuration

_posts/languages/php/2000-01-01-wordpress.md
=> WordPress connects to MySQL with TLS

_includes/nginx_versions.md, _posts/languages/php/2000-01-01-start.md, _posts/platform/deployment/buildpacks/2000-01-01-nginx.md
=> Add list of supported Nginx versions

changelog/tools/_posts/2019-12-30-phpmyadmin-5.0.0.md
Tweet:
> [Changelog] phpMyAdmin - Version 5.0.0 deployed https://changelog.scalingo.com #PaaS #changelog #phpmyadmin
=> [changelog] phpMyAdmin 5.0.0

_posts/platform/internals/2000-01-01-router-error-codes.md
=> Error code is 502 when all containers are in quarantine

changelog/tools/_posts/2020-01-08-phpmyadmin-5.0.1.md
Tweet:
> [Changelog] phpMyAdmin - Version 5.0.1 deployed https://changelog.scalingo.com #PaaS #changelog #phpmyadmin
=> [changelog] phpMyAdmin 5.0.1

_posts/platform/app/2000-01-01-log-drain.md
=> make log drain available upon request instead of private beta 

README.md, _posts/platform/deployment/buildpacks/2000-01-01-custom.md, _posts/platform/internals/stacks/2000-01-01-scalingo-14-stack.md, _posts/platform/internals/stacks/2000-01-01-scalingo-18-stack.md, _posts/platform/internals/stacks/2000-01-01-stacks.md
Linked to https://github.com/Scalingo/one-stop-shop/issues/30
=> Rename builders to scalingo-14 and scalingo-18

_posts/languages/php/2000-01-01-start.md, changelog/buildpacks/_posts/2020-01-16-php-symfony-5.md, changelog/buildpacks/_posts/2020-01-17-php-symfony-5.md
Tweet:
> [Changelog] Buildpacks - PHP - Support of Symfony 5 https://changelog.scalingo.com #php #Symfony #PaaS #update #changelog
=> [changelog] Symfony 5

_posts/languages/php/2019-02-07-php-nodejs.md
=> [PHP + Node.js] Fix order of buildpacks

_posts/languages/php/2000-01-01-start.md, _posts/languages/php/2019-02-07-php-nodejs.md
=> [PHP + Node.js] Better explain the default Node.js support in PHP buildpack

changelog/databases/_posts/2020-01-23-mysql-5.7.29-1.markdown
Tweet:
> [changelog] Databases - MySQL - New version available: 5.7.29-1 https://doc.scalingo.com/changelog #mysql #changelog #paas
=> [changelog] MySQL 5.7.29-1

_posts/languages/php/2000-01-01-start.md
=> Clarify how to configure WEB_CONCURRENCY

changelog/tools/_posts/2020-02-04-adminer.4.7.6.md
Tweet:
> [Changelog] Adminer - Version 4.7.6 deployed https://changelog.scalingo.com #paas #changelog #adminer
=> [changelog] Adminer 4.7.6

app/javascript/css/application.scss, changelog.html
Fix #320 
https://documentation-service-pr456.scalingo.io/changelog
=> Add a link to share on Twitter

changelog/buildpacks/_posts/2020-02-11-php-mongodb-ext-1.7.1.markdown
Tweet:
> [Changelog] Buildpacks - PHP - Support of extension mongodb version 1.7.1
> https://changelog.scalingo.com #php #MongoDB #PaaS #update #changelog
=> [changelog] PHP MongoDB driver 1.7.1

_posts/platform/deployment/buildpacks/2000-01-01-nginx.md
=> [Nginx] Explain the new servers.conf.erb configuration file

_posts/platform/internals/2000-01-01-regions.md
Am I missing some information?
Fix #811
=> Highlight difference between regions

_posts/platform/databases/2000-01-01-restore-backup.md
=> Clarify the use of dbclient-fetcher to restore in a one-off

_includes/info_command_line_tool.md, _posts/databases/elasticsearch/2000-01-01-start.md, _posts/databases/influxdb/2000-01-01-start.md, _posts/databases/mongodb/2000-01-01-start.md, _posts/databases/mysql/2000-01-01-start.md, _posts/databases/postgresql/2000-01-01-start.md, _posts/databases/redis/2000-01-01-start.md, _posts/platform/app/2000-01-01-tasks.md, _posts/platform/databases/2000-01-01-access.md
=> Better explanation of what a one-off is

_includes/footer.html
Related to Scalingo/one-stop-shop#25
=> scalingostatus.com is the new status.scalingo.com

_posts/languages/php/2000-01-01-wordpress.md
=> Update WordPress doc for Bedrock and add some more informations about it

index.md
=> Add a 'view all' button to see all languages

_posts/platform/app/2000-01-01-domain.md
=> [Soft Limit] 5 domains per app

_posts/languages/php/2000-01-01-symfony.md
=> [Symfony] Disable DebugBundle in prod

_posts/languages/erlang/2000-01-01-start.md
Related to Scalingo/erlang-buildpack#2
=> Update Erlang buildpack

changelog/buildpacks/_posts/2020-03-24-erlang-rebar3.markdown
Tweet:
> [Changelog] Buildpacks - Erlang - Support of rebar3 https://changelog.scalingo.com #erlang #changelog #PaaS
=> [changelog] Erlang new upstream buildpack

changelog/tools/_posts/2020-03-24-phpmyadmin-5.0.2.md
Related to https://github.com/Scalingo/scalingo-phpmyadmin/pull/4
Tweet:
> [Changelog] phpMyAdmin - Version 5.0.2 deployed https://changelog.scalingo.com #PaaS #changelog #phpmyadmin
=> [changelog] phpMyAdmin 5.0.2

changelog/cli/_posts/2020-03-24-1-16-7.md
Tweet:
> [Changelog] CLI - Release of version 1.16.7 https://cli.scalingo.com - More news at https://changelog.scalingo.com #cli #paas #changelog #bugfix
=> [changelog] CLI 1.16.7

changelog/buildpacks/_posts/2020-03-25-php-7.4.4.markdown
Changelog php 7.4.4
Related to https://github.com/Scalingo/php-buildpack/issues/139
=> Changelog php 7.4.4

_posts/platform/internals/2000-01-01-regions.md
Ooops, sorry the branch name is wrong.
=> [Regions] how to change the default CLI region

_posts/platform/cli/2000-01-01-start.md
=> [CLI] List of domain name it communicates with

_posts/platform/internals/2000-01-01-routing.md
=> Requests compression

_posts/languages/php/2000-01-01-start.md
=> [PHP] No specific configuration

_posts/languages/php/2000-01-01-laravel.md
=> Add a Laravel cron example

_posts/platform/app/2000-01-01-regions-migration.md
I decided to not include the complete output of the CLI to shorten the page.
https://documentation-service-pr884.osc-fr1.scalingo.io/platform/app/regions-migration
=> Add region migration page

_posts/platform/app/2000-01-01-cloudflare-scalingo-app.md, _posts/platform/app/2000-01-01-sucuri-scalingo-app.md
=> Add Sucuri page: explain how to enable full SSL mode

_posts/databases/mysql/2000-01-01-start.md, _posts/databases/postgresql/2000-01-01-dump-restore.md, _posts/platform/databases/2000-01-01-adminer.md, _posts/platform/internals/2000-01-01-regions.md
=> phpMyAdmin and Adminer have a .com domain name

changelog/cli/_posts/2020-04-01-1-16-8.md
Tweet:
> [Changelog] CLI - Release of version 1.16.8 https://cli.scalingo.com - More news at https://changelog.scalingo.com #cli #paas #changelog #bugfix
=> [changelog] CLI 1.16.8

.gitignore, _posts/languages/nodejs/2000-01-01-start.md
=> [Node.js] Update the scalingo-postbuild step

_posts/platform/deployment/buildpacks/2000-01-01-custom.md
Fix #905 Use a Custom Buildpack - mention stack env
=> Fix #905 mention stack env

_config.yml
Waiting for Soulou to accept my ownership transfer request of
https://github.com/EtienneM/sample-erlang so that it gets renamed to
https://github.com/Scalingo/sample-erlang.
=> Add Erlang sample

_posts/platform/app/2000-01-01-regions-migration.md
Makes the process clearer and more detailed
=> Rewrite region migration page

_posts/platform/internals/stacks/2000-01-01-stacks.md
=> [Stack] Clarify migration instructions

_posts/platform/app/2000-01-01-autoscaler.md
=> Autoscaling: precisions about how values are looked up

_posts/languages/php/2000-01-01-laravel.md
Fix  #870 - Passport configuration for Laravel
=> Fix  #870 - Passport configuration for Laravel

_posts/platform/internals/2000-01-01-regions.md
=> mention migration page

_posts/platform/app/2000-01-01-custom-error-page.md
=> Explain the four different types of customizable error pages

_posts/platform/app/2000-01-01-app-manifest.md
=> first-deploy clarification

_posts/platform/databases/2000-01-01-intro.md
=> minor typo

_posts/platform/app/2000-01-01-regions-migration.md
=> mention storky 

_posts/platform/getting-started/2000-01-01-getting-started-with-elk.md
=> Explain how to install and configure curator

_posts/platform/cli/2000-01-01-start.md
It is hard to test whether it fixes the related issue or not. Let's merge this and see how Algolia search engine indexes the new page.
Related to #419
=> Rephrase to improve SEO via Algolia search

_posts/platform/app/2000-01-01-postdeploy-hook.md
=> Explain the difference between Scalingo postdeploy and Heroku release phase

changelog/cli/_posts/2020-06-09-1-18-0.md
Tweet:
> [Changelog] CLI - Release of version 1.18.0 https://cli.scalingo.com - More
> news at https://changelog.scalingo.com #cli #paas #changelog #bugfix
=> [changelog] CLI 1.18.0

changelog/cli/_posts/2020-06-09-1-18-1.md
> [Changelog] CLI - Release of version 1.18.1 https://cli.scalingo.com - More news at https://changelog.scalingo.com #cli #paas #changelog #bugfix
=> [changelog] CLI 1.18.1

_posts/languages/php/2000-01-01-start.md
=> Explain the NEW_RELIC_APP_NAME env variable

_posts/databases/mongodb/2000-01-01-compass.md, _posts/databases/mongodb/2000-01-01-robo3t.md, _posts/platform/databases/2000-01-01-access.md
The two ways being Encrypted tunnel and Internet accessibility
Fix #974
=> MongoDB GUIs can reach MongoDB in two ways

app/javascript/js/search.js
Waiting for me to find a fix, I would like to revert the changes introduced in #992.
Related to https://github.com/Scalingo/one-stop-shop/issues/145
=> Remove the piece of code which breaks the search

_posts/databases/elasticsearch/2000-01-01-start.md, _posts/databases/influxdb/2000-01-01-start.md, _posts/databases/mongodb/2000-01-01-start.md, _posts/databases/mysql/2000-01-01-start.md, _posts/platform/databases/2000-01-01-intro.md
=> Add a 'Communication With TLS' section

_posts/platform/app/2000-01-01-tasks.md
https://documentation-service-pr998.osc-fr1.scalingo.io/platform/app/tasks#audit-logs
Fix #976
=> Add a word about audit logs

_includes/encryption_at_rest.md, _posts/platform/databases/2000-01-01-intro.md
a small typo, and wrong key size
=> fix encryption at rest description

_posts/databases/postgresql/2000-01-01-start.md
Add some precisions about PG PITR
=> Pg PITR precisions

_posts/platform/deployment/buildpacks/2000-01-01-nginx.md
=> [Nginx] Clarify we need to create a new Scalingo application

_posts/platform/deployment/2000-01-01-deploy-with-gitlab.md, _posts/platform/deployment/continuous-integration/2000-01-01-deploy-scalingo-from-gitlab.md, _posts/platform/deployment/continuous-integration/2000-01-01-intro.md
=> Scalingo deployment with GitLab CI/CD

_posts/databases/postgresql/2000-01-01-dump-restore.md
=> [pg_dump/pg_restore] Use the --no-comments flag

_posts/platform/getting-started/2000-01-01-common-deployment-errors.md
Like https://doc.scalingo.com/platform/deployment/limits#limits
=> Update the image size limit

_posts/platform/internals/2000-01-01-regions.md
I also added a word about agora-fr1 deprecation.
Fix #970
=> Add DB API endpoints

_posts/platform/deployment/2000-01-01-limits.md
=> [Deployments] Add the max concurrent deployment limit

_posts/platform/deployment/buildpacks/2000-01-01-ssh-key.md
=> [SSH Key] Buildpack useful during build

_posts/languages/php/2000-01-01-laravel.md
=> [Laravel] Instructions to generate and set APP_KEY

_posts/databases/mongodb/2000-01-01-dump-restore.md
=> [mongorestore] use --uri instead of multiple options

_posts/platform/app/2000-01-01-slugignore.md
=> [Slugignore] It supports wildcards

_posts/platform/deployment/buildpacks/2000-01-01-ffmpeg.md
=> [FFmpeg] Document the installation of ffprobe

_posts/platform/app/2000-01-01-log-drain.md
Related to https://github.com/Scalingo/api/issues/1728
Related to https://github.com/Scalingo/api/issues/1722
Related to https://github.com/Scalingo/api/issues/1734
=> Add log drains addons

_includes/ssh_urls.md, _posts/databases/mysql/2000-01-01-start.md, _posts/databases/postgresql/2000-01-01-dump-restore.md, _posts/platform/app/2000-01-01-domain.md, _posts/platform/app/2000-01-01-regions-migration.md, _posts/platform/databases/2000-01-01-adminer.md, _posts/platform/deployment/continuous-integration/2000-01-01-deploy-scalingo-from-circle-ci.md, _posts/platform/internals/2000-01-01-network.md, _posts/platform/internals/2000-01-01-regions.md
The only remaining occurences are:
- In some changelog entries
- In the page about region migrations, but just as an example of migration: https://doc.scalingo.com/platform/app/regions-migration
=> Remove occurences of agora-fr1

_posts/databases/mysql/2000-01-01-mysql-8-prerequisites.md, _posts/databases/mysql/2000-01-01-start.md
I merge this branch into #845. I did this to evaluate separately this paragraph which is kinda sensitive as it suggests database modifications to the user.
=> Explain MySQL 8 prerequisite

_posts/databases/mysql/2000-01-01-mysql-8-prerequisites.md, _posts/databases/mysql/2000-01-01-start.md, _posts/databases/postgresql/2000-01-01-start.md, _posts/databases/redis/2000-01-01-start.md, changelog/databases/_posts/2020-02-26-mysql-ha-cluster.markdown, changelog/databases/_posts/2020-09-02-mysql-ha-cluster.markdown
It's already reviewable just wait for the official release to merge it.
Fix #792
=> [MySQL] Doc about HA

_posts/databases/mysql/2000-01-01-mysql-8-prerequisites.md
=> Add example output in MySQL 8 prerequisites page

_posts/platform/deployment/2000-01-01-deploy-with-git.md
=> Document git clone operations

_posts/languages/php/2000-01-01-start.md
Related to https://github.com/Scalingo/php-buildpack/issues/160
=> Add mcrypt to the list of available extensions

_posts/platform/app/2000-01-01-log-drain.md, _posts/platform/app/2000-01-01-logs.md
=> Better introduce logs and explain them

_posts/languages/php/2000-01-01-wordpress.md
=> [WordPress] Fix a couple of instructions with more up-to-date practice

changelog/buildpacks/_posts/2020-09-24-php-7.4.10.markdown
https://github.com/Scalingo/php-buildpack/issues/158
=> 2020-09-24-php-7.4.10.markdown

_posts/platform/app/2000-01-01-long-process.md
=> Explain how to deal with long processes in a web app

_posts/languages/php/2000-01-01-laravel.md
=> [Laravel] Add correct flags to migration postdeploy

_posts/databases/mongodb/2000-01-01-start.md
=> Describe MongoDB Replica set architecture

_posts/platform/getting-started/2000-01-01-heroku-compatibility.md
=> [Heroku Compat] Add a word about app.json

_posts/platform/app/2000-01-01-environment.md
=> Explain how to deal with multi-lines environment variables

_posts/platform/databases/2000-01-01-intro.md
=> Add HAProxy timeouts

_posts/languages/nodejs/2000-01-01-puppeteer.md, _posts/languages/php/2019-02-07-php-nodejs.md, _posts/languages/python/django/2000-01-01-geodjango.md, _posts/languages/ruby/2000-01-01-private-gem-from-git-on-scalingo.md, _posts/platform/deployment/buildpacks/2000-01-01-apt.md, _posts/platform/deployment/buildpacks/2000-01-01-cairo.md, _posts/platform/deployment/buildpacks/2000-01-01-ffmpeg.md, _posts/platform/deployment/buildpacks/2000-01-01-graphicsmagick.md, _posts/platform/deployment/buildpacks/2000-01-01-jemalloc.md, _posts/platform/deployment/buildpacks/2000-01-01-locale.md, _posts/platform/deployment/buildpacks/2000-01-01-multi.md, _posts/platform/deployment/buildpacks/2000-01-01-ssh-key.md, _posts/platform/deployment/buildpacks/2000-01-01-wkhtmltopdf.md, _posts/platform/getting-started/2000-01-01-getting-started-with-grafana.md, _posts/platform/getting-started/2000-01-01-getting-started-with-metabase.md
=> Instruction to install Puppeteer

_posts/platform/app/2000-01-01-review-apps.md
=> [Review App] No automatic creation after a new deployment

changelog/buildpacks/_posts/2020-10-16-php-mongodb-ext-1.8.1.markdown
Related to https://github.com/Scalingo/php-buildpack/issues/137
> [Changelog] Buildpacks - PHP - Support of extension mongodb version 1.8.1 https://changelog.scalingo.com #php #MongoDB #PaaS #update #changelog
=> [changelog] PHP MongoDB driver 1.8.1

_posts/platform/app/2000-01-01-app-manifest.md
=> [JSON Manifest] How to specify an addon version

_posts/platform/app/2000-01-01-postdeploy-hook.md
=> [Postdeploy] Mention container size

_posts/languages/php/2000-01-01-laravel.md
=> [Laravel] Explain how to use S3

_posts/databases/influxdb/2000-01-01-start.md
Fix #862
Kind of related to #825
=> [InfluxDB] Explain how to control memory usage

_posts/databases/postgresql/2000-01-01-start.md
=> [PostgreSQL] Explain how does it uses the RAM

_posts/languages/php/2000-01-01-start.md
https://documentation-service-pr1096.osc-fr1.scalingo.io/languages/php/start#select-a-composer-version
Related to Scalingo/php-buildpack#168
=> Document how to specify the Composer version

_posts/languages/php/2000-01-01-start.md, changelog/buildpacks/_posts/2020-11-09-php-7.4.12.markdown, changelog/buildpacks/_posts/2020-11-09-php-composer-2.0.6.markdown, changelog/buildpacks/_posts/2020-11-09-php-mongodb-ext-1.8.2.markdown
- MongoDB driver
- Composer
- PHP minor versions
Tweet:
> [Changelog] Buildpacks - PHP - Various minor releases related to PHP https://changelog.scalingo.com #php #changelog #PaaS
=> [PHP] Various PHP releases

_posts/databases/mongodb/2000-01-01-dump-restore.md, _posts/databases/mysql/2000-01-01-dump-restore.md, _posts/databases/postgresql/2000-01-01-dump-restore.md
Fix [OPSB-139]
[OPSB-139]: https://scalingo.atlassian.net/browse/OPSB-139
=> Document how to pg_dump and restore using Internet Accessibility

_posts/platform/app/2000-01-01-app-manifest.md, changelog/integrations/_posts/2020-11-18-scalingo.json_project_dir.markdown
Fix [OPSB-155] and [OPSB-156]
[OPSB-155]: https://scalingo.atlassian.net/browse/OPSB-155
[OPSB-156]: https://scalingo.atlassian.net/browse/OPSB-156
=> Document and changelog for the scalingo.json detection under PROJECT_DIR

_posts/databases/postgresql/2000-01-01-start.md
Adding a point about PG client customization
=> PG client customization

_posts/platform/app/2000-01-01-tasks.md
=> [Detached One-Off] Add a warning that they are un-killable

_posts/platform/app/2000-01-01-postdeploy-hook.md
It's hard to test if it improves the ranking by Algolia but let's try it that way
Related to #1123
=> Make 'Database Migrations' a title for better SEO

_config.yml, _posts/languages/nodejs/2000-01-01-websocket-web-same-port.md
Fix https://github.com/Scalingo/documentation/issues/1116
=> Add the sample Socket.IO

changelog/tools/_posts/2020-12-17-phpmyadmin-5.0.4.md
~Not yet in prod. Tests in staging first~
=> [changelog] phpMyAdmin 5.0.4

changelog/tools/_posts/2020-12-17-adminer.4.7.8.md
~Not yet deployed. Waiting for GitHub integration on the app.~
=> [changelog] Adminer 4.7.8

_posts/platform/app/2000-01-01-app-manifest.md
=> postdeploy in scalingo.json is deprecated

_posts/languages/nodejs/2000-01-01-start.md
Adding a section about nextjs dynamic port (reopened on a better page)
=> Adding a section about nextjs dynamic port

_includes/database_backups.md
=> [Backup Retention] Explain policy when database is removed from application

_posts/languages/ruby/rails/2000-01-01-start.md
=> [Rails] Common error for Webpacker

_posts/addons/scalingo-openvpn/2000-01-01-start.md
=> [OpenVPN] Mention it's impossible to use dhcp-option on Scalingo

_posts/platform/app/2000-01-01-logs.md
=> Document how to get addons' logs

_posts/platform/app/2000-01-01-logs.md
=> [Logs] Lines order is not guaranteed

_posts/languages/ruby/2000-01-01-start.md
=> Mention we support all Rails versions

_posts/platform/app/2000-01-01-tasks.md
=> [One-Off] Max file size is 100 MiB

_posts/platform/app/2000-01-01-web-less-app.md
=> Deploy a web-less application

_posts/platform/app/2000-01-01-slugignore.md
Fixing the PHP apps section ([Webpack](https://webpack.js.org/), not [Webpacker](https://github.com/rails/webpacker)), and other minor rewording.
=> Update slugignore documentation

changelog/databases/_posts/2020-02-03-redis.5.0.10-1.markdown
Tweet:
> [Changelog] - Redis - New version: 5.0.10-1 - https://changelog.scalingo.com #redis #changelog #PaaS
=> [changelog] Redis 5.0.10-1

changelog/tools/_posts/2021-02-08-adminer.4.7.9.md
Tweet:
> [Changelog] Adminer - Version 4.7.9 deployed https://changelog.scalingo.com #paas #changelog #adminer
=> [changelog] Adminer 4.7.9

_posts/platform/getting-started/2000-01-01-getting-started-with-sonarqube.md
Related to https://github.com/Scalingo/sonarqube-buildpack/issues/1
=> docs(sonarqube): add support for SonarQube plugins

_posts/languages/java/2000-01-01-start.md, changelog/buildpacks/_posts/2021-02-09-maven-3.6.2.md
Related to https://github.com/Scalingo/java-buildpack/pull/7
=> docs(maven): add support for Maven 3.5.4 and 3.6.2

_posts/platform/app/2000-01-01-run-scheduled-tasks.md
Build only once the cron tasks
=> Fix a php code mistake

_posts/languages/php/2000-01-01-start.md
Related to https://github.com/Scalingo/php-buildpack/issues/187
=> [OPSB-238] Add documentation about nginx-http-includes extra key of composer.json

_posts/languages/php/2000-01-01-start.md, changelog/buildpacks/_posts/2021-02-19-php-8.0.2.markdown
Related to https://github.com/Scalingo/php-buildpack/issues/187
=> 2021-02-19-php-8.0.2.markdown

.github/dependabot.yml
It currently open PRs whenever a new update exists...
=> feat(dependabot): should trigger every Monday

_posts/languages/php/2000-01-01-start.md, changelog/buildpacks/_posts/2021-03-10-new-php-versions.md
Fix https://github.com/Scalingo/php-buildpack/issues/188
Fix https://github.com/Scalingo/php-buildpack/issues/186
=> releases(php): Add new PHP and composer versions

_posts/platform/deployment/2000-01-01-deploy-with-git.md
Related to [GRR-127]
[GRR-127]: https://scalingo.atlassian.net/browse/GRR-127
=> [Git deploy]: Handle a shallow error

_posts/platform/getting-started/2000-01-01-getting-started-with-elk.md
The [headers][request_path] does not seem to be the correct header anymore. Using request_path instead yields the expected values.
=> update logstash configuration

_posts/platform/internals/2000-01-01-billing.md
Review URL: https://documentation-service-pr990.scalingo.io/platform/internals/billing
=> Fix: billing profile link + add how to fill BP

changelog/api/_posts/2021-03-23-apps-ps.md
Related to [OPSB-254]
[OPSB-254]: https://scalingo.atlassian.net/browse/OPSB-254
=> docs(changelog): new API route for app containers list

_posts/platform/app/2000-01-01-logs.md
=> Add paragraph about Log retention on Scalingo

_posts/platform/internals/2000-01-01-recovery-management.md
=> Add more information about disaster recovery, especially the redundancy of backups

_posts/platform/internals/2000-01-01-recovery-management.md
Page has been updated in https://github.com/Scalingo/documentation/pull/1240
=> fix: modified_at field should have been updated

_posts/platform/app/2000-01-01-scm-integration.md
https://documentation-service-pr1249.osc-fr1.scalingo.io/platform/app/scm-integration#deployments
=> docs(scm): add a warning about GitHub Actions

_posts/platform/getting-started/2000-01-01-getting-started-with-elk.md
…at least
Otherwise it doesn't start.
=> guide(logstash) Instructu the user to scale the app to a L container at least

Gemfile, Gemfile.lock, config.ru
Required to get the feed via XHR requests.
=> Configure CORS for changelog feed

_posts/languages/nodejs/2000-01-01-puppeteer.md
=> docs(puppeteer): STACK env variable must be set

changelog/buildpacks/_posts/2021-06-07-php-composer-2.1.2.markdown
Tweet:
> [Changelog] Buildpacks - PHP - Support of Composer 2.1.2 https://changelog.scalingo.com #php #composer #changelog #PaaS
Fix https://github.com/Scalingo/php-buildpack/issues/206
=> docs(changelog): Composer 2.1.2

changelog/api/_posts/2021-06-07-app-name-48-chars.md
Related to [API-31]
To merge once API is deployed
[API-31]: https://scalingo.atlassian.net/browse/API-31
=> Add changelog entry related to API change, app name length max is 48

_posts/platform/app/2000-01-01-autoscaler.md
I also changed the screenshots on the CDN.
Related to https://github.com/Scalingo/one-stop-shop/issues/260
=> docs(autoscaler): not upon request anymore

_posts/languages/elixir/2000-01-01-start.md
Do you think this wording is better to explain community buildpack?
=> docs(elixir): rephrase explanation about community buildpack

_posts/addons/scalingo-docker-image/2000-01-01-start.md
=> docs(docker): fix Docker registry URL

_posts/languages/ruby/2000-01-01-start.md
=> docs(ruby): update the Ruby supported versions

_posts/languages/nodejs/2000-01-01-deployment-errors.md
Because the solution to my problem was not on the link indicated by the error
=> Specific next.js solution

changelog/api/_posts/2021-09-08-cron-tasks-list.md
Merge the dev doc at the same time as this PR: https://github.com/Scalingo/developers-documentation/pull/162
=> Add changelog entry for cron tasks endpoints

_includes/upon_request.md, _posts/languages/php/2000-01-01-laravel.md, _posts/platform/app/2000-01-01-run-scheduled-tasks.md
Fix [CRON-6]
[CRON-6]: https://scalingo.atlassian.net/browse/CRON-6
=> docs(cron): explain the new feature

_includes/nginx_versions.md, _posts/languages/php/2000-01-01-start.md, changelog/buildpacks/_posts/2021-09-09-nginx-1.20.1.md, changelog/buildpacks/_posts/2021-09-09-php-8.0.10.md, changelog/buildpacks/_posts/2021-09-09-php-apcu-ext-5.20.0.md, changelog/buildpacks/_posts/2021-09-09-php-composer-2.1.6.md, changelog/buildpacks/_posts/2021-09-09-php-ds-ext-1.3.0.md, changelog/buildpacks/_posts/2021-09-09-php-event-ext-3.0.5.md, changelog/buildpacks/_posts/2021-09-09-php-igbinary-ext-3.2.6.md, changelog/buildpacks/_posts/2021-09-09-php-imagick-ext-3.5.1.md, changelog/buildpacks/_posts/2021-09-09-php-mongodb-ext-1.10.0.md, changelog/buildpacks/_posts/2021-09-09-php-redis-ext-5.3.4.md
Tweets:
> [Changelog] Buildpacks - PHP - Support of Composer 2.1.6 https://changelog.scalingo.com #php #composer #changelog #PaaS
> [Changelog] Buildpacks - PHP - Update multiple extensions https://changelog.scalingo.com #php #PaaS #update #changelog
> [Changelog] Buildpacks - PHP - Support of PHP 8.0.10, 7.4.23 and 7.3.30 https://changelog.scalingo.com #php #changelog #PaaS
> [Changelog] Buildpacks - Nginx - Support of Nginx 1.21.3 https://changelog.scalingo.com #nginx #changelog #PaaS
Fix https://github.com/Scalingo/php-buildpack/issues/207
Fix https://github.com/Scalingo/php-buildpack/issues/176
Fix https://github.com/Scalingo/php-buildpack/issues/208
=> docs(changelog): various upgrades related to PHP

_posts/platform/getting-started/2000-01-01-getting-started-with-metabase.md
This method is only working for our application, not the users' one.
=> Remove wrong update method

_includes/database_backups.md
=> docs(backups): scheduled date is not execution date

_posts/platform/app/2000-01-01-tasks.md
Make the documentation about one-off clearer.
Thanks @vonox7
=> Explain all commands needed for one-off container management

_posts/languages/java/2000-01-01-gradle.md
Related to https://github.com/Scalingo/gradle-buildpack/issues/10
=> docs(gradle): Specify that Gradle should be updated when use a more recent JDK version

_posts/platform/app/2000-01-01-log-drain.md
=> docs(log-drain): explain quarantine mechanism

package.json, yarn.lock
Forcing resolution for now to make it pass https://github.com/imagemin/imagemin-pngquant/issues/46
Forcing resolution will froze the version. As a side effect, any vulnerability fix will not be installed.
Alternative is to add the apt buildpack and install the libpng-dev
=> Pngquant got a breaking change

_posts/languages/python/2020-11-23-SQLAlchemy.md
Doc for https://github.com/Scalingo/python-buildpack/pull/46
=> feat: new doc for SQLAlchemy

_posts/platform/deployment/2000-01-01-one-click-deploy.md, _posts/platform/getting-started/2000-01-01-getting-started-with-metabase.md
=> How to update 1click app 

_posts/platform/deployment/buildpacks/2000-01-01-apt.md
=> docs(apt): document APT_FILE_MANIFEST

_posts/platform/app/2000-01-01-procfile.md
=> docs(Procfile): the command part is any Bash command

_posts/databases/mongodb/2000-01-01-dump-restore.md, _posts/databases/mysql/2000-01-01-dump-restore.md, _posts/databases/postgresql/2000-01-01-dump-restore.md
=> docs: mention dbclient-fetcher for all DB types

_posts/languages/php/2000-01-01-laravel.md
Ajout d'informations sur le déploiement avec les `.buildpacks` et la connexion de DB simplifiée grâce à la clé `'url'`.
Consolidation des infos de déploiement suite à un échange avec le support. Il me manquait la config des buildpacks ;)
=> Déploiement Laravel

_posts/platform/deployment/2000-01-01-deploy-java-jar-war.md
=> docs(jar): how to deploy

_posts/languages/nodejs/2000-01-01-puppeteer.md
Replaces https://github.com/Scalingo/documentation/pull/1467
=> docs(puppeteer): use the APT buildpack

_posts/languages/nodejs/2000-01-01-yarn-2.md
Related to https://github.com/Scalingo/nodejs-buildpack/issues/50
Related to https://github.com/Scalingo/nodejs-buildpack/issues/50
=> Yarn 2/Yarn 3 documentation page, in order to update node buildpack to get this compatibility

_posts/platform/app/2000-01-01-tasks.md
=> docs(one-off): document 1h inactivity

_posts/platform/app/task-scheduling/2000-01-01-scalingo-scheduler.md
=> docs(scheduler): dates are in UTC

changelog/tools/_posts/2022-01-10-adminer.4.8.1.md
Tweet:
> [Changelog] Adminer - Version 4.8.1 deployed https://changelog.scalingo.com #paas #changelog #adminer
Related to https://github.com/Scalingo/adminer/issues/4
=> docs(changelog): deploy adminer 4.8.1

_posts/languages/nodejs/2000-01-01-start.md
Related to https://github.com/Scalingo/nodejs-buildpack/pull/53
=> docs(nodejs-version): Update node.js default version

changelog/tools/_posts/2022-01-25-phpmyadmin-5.1.2.md
Tweet:
> [Changelog] phpMyAdmin - Version 5.1.2 deployed https://changelog.scalingo.com #paas #changelog #phpMyAdmin
Fix https://github.com/Scalingo/scalingo-phpmyadmin/issues/11
=> docs(changelog): phpMyAdmin 5.1.2

_posts/platform/app/2000-01-01-regions-migration.md
Commit 73dd4afa: I feel like it makes more sense today
https://documentation-service-pr1529.osc-fr1.scalingo.io/platform/app/regions-migration#introduction
Fix #999
=> docs(regions-migration): add what is NOT migrated

_posts/platform/app/2000-01-01-procfile.md
https://documentation-service-pr1534.osc-fr1.scalingo.io/platform/app/procfile#removing-a-container-type
Fix #1533
=> docs(Procfile): explain how to remove an entry

_posts/databases/elasticsearch/2000-01-01-start.md
=> docs(elasticsearch): mention 0-downtime for plan change

_posts/languages/python/django/2000-01-01-start.md
https://documentation-service-pr1528.osc-fr1.scalingo.io/languages/python/django/start#define-how-to-start-your-application
Fix #815
=> docs(django): explain how to use a ASGI server

_posts/platform/app/2000-01-01-review-apps.md
https://documentation-service-pr1530.osc-fr1.scalingo.io/platform/app/review-apps#what-are-review-apps
Fix #1163
=> docs(review-apps): creation with the CLI

src/_posts/databases/postgresql/2000-01-01-dump-restore.md, src/_posts/databases/postgresql/timescaledb/2000-01-01-dump-restore.md, src/_posts/databases/postgresql/timescaledb/2000-01-01-intro.md
Do not merge, wait for https://github.com/Scalingo/documentation/pull/1520 to be merged before.
Fix #1555
=> Do not restore on PostgreSQL TimescaleDB

src/_posts/databases/postgresql/timescaledb/2000-01-01-data-retention.md
With previous versions, databases with a large number of hypertables would fail applying this policy
```
ERROR:  out of shared memory
HINT:  You might need to increase max_locks_per_transaction.
```
Because by default PostgreSQL is doing the execution of one function in
one single transaction
With the new method, each chunk deletion is commited and there is a lot
message stating for the execution
```
promscale_5801=> call generic_retention(config => '{"drop_after":"1 month"}');
NOTICE:  prom_data.go_memstats_mcache_inuse_bytes
NOTICE:  prom_data.process_cpu_seconds_total
NOTICE:  prom_data.gitaly_supervisor_health_checks_total
NOTICE:  prom_data.go_memstats_gc_sys_bytes
NOTICE:  prom_data.gitaly_repository_optimizerepository_empty_dir_removal_total
NOTICE: …
```
=> [Timescaledb] Improve retention policy procedure

src/changelog/databases/_posts/2022-03-10-mysql-8.0.28-1.md
Tweet:
> [Changelog] - MySQL - New version: 8.0.28-1 - https://changelog.scalingo.com #mysql #changelog #PaaS
=> docs(changelog): MySQL 8.0.28-1

src/_posts/platform/internals/2000-01-01-recovery-management.md
Security Policy states that our RPO for PG is 30 minutes
See https://github.com/Scalingo/specifications/blob/ce7b0b9a0aa38df09939c3ebf1351546723c2f8c/isms/Information-Systems-Security-Policy-Fr.md?plain=1#L158
=> Correct RPO to match with Security Policy

src/_posts/languages/php/2000-01-01-start.md, src/changelog/buildpacks/_posts/2022-03-16-php-ext-apfd.md
Related to https://github.com/Scalingo/php-buildpack/issues/237
=> docs(php): add support for apfd PHP extension

src/changelog/tools/_posts/2022-03-16-phpmyadmin-5.1.3.md
Tweet:
> [Changelog] phpMyAdmin - Version 5.1.3 deployed https://changelog.scalingo.com #paas #changelog #phpMyAdmin
Fix https://github.com/Scalingo/scalingo-phpmyadmin/issues/12
=> docs(changelog): phpMyAdmin 5.1.3

src/_posts/platform/internals/2000-01-01-network.md
Related to [SRE-421]
[SRE-421]: https://scalingo.atlassian.net/browse/SRE-421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feature(network) Document platform rate limiting

src/_includes/db_ca_endpoints.md, src/_includes/mongo_db_tunnel.md, src/_includes/ssh_endpoints.md, src/_posts/databases/mongodb/2000-01-01-compass.md, src/_posts/platform/databases/2000-01-01-access.md
=> docs(mongodb-compass): Improve MongoDB Compass page

src/_posts/platform/getting-started/2000-01-01-how-to-migrate-from-heroku.md
=> Fix #1621 Updating obsolete Heroku migration page

src/_posts/platform/getting-started/2000-01-01-how-to-migrate-from-heroku.md
Last modified date was not accurate.
=> Last modified date was not accurate on the Heroku migration procedure

src/_posts/databases/redis/2000-01-01-start.md
=> docs(redis): number of databases is 5

src/_posts/languages/ruby/rails/2000-01-01-start.md
Related to https://app.intercom.com/a/inbox/w4oogu7s/inbox/shared/all/conversation/12375700069457
=> fix(rails): add a note to specify that we create a database at the boot of DB addon

src/changelog/buildpacks/_posts/2022-07-12-php-mongodb-ext-1.13.0.md
Related to https://github.com/Scalingo/php-buildpack/issues/259
=> releases(php-mongodb) Release mongodb 1.13.0

src/_posts/security/procedures/2000-01-01-gdpr.md
[COMP-280]
[COMP-280]: https://scalingo.atlassian.net/browse/COMP-280?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add GDPR data access procedures

src/_posts/security/procedures/2000-01-01-gdpr.md
[COMP-280]
[COMP-280]: https://scalingo.atlassian.net/browse/COMP-280?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update modification date

src/changelog/tools/_posts/2022-07-21-phpmyadmin-5.2.0.md
Tweet:
> [Changelog] phpMyAdmin - Version 5.2.0 deployed https://changelog.scalingo.com #paas #changelog #phpMyAdmin
Fix https://github.com/Scalingo/scalingo-phpmyadmin/issues/13
=> docs(changelog): phpMyAdmin 5.2.0

src/_posts/platform/getting-started/2000-01-01-getting-started-with-elk.md
Update documentation so that Curator uses our Scheduler and not a
Shellscript.
Fixes #1707
=> docs(documentation): schedule curator with our Scheduler

src/_posts/platform/app/task-scheduling/2000-01-01-scalingo-scheduler.md
Related to [SRE-386]
[SRE-386]: https://scalingo.atlassian.net/browse/SRE-386?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(cron tasks) Document the jitter time

src/changelog/databases/_posts/2022-08-11-postgresql-12.11.0-3.markdown
Fix [SRE-700]
[SRE-700]: https://scalingo.atlassian.net/browse/SRE-700?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feature(changelog) Release PostgreSQL 12.11.0-3

src/_posts/addons/2000-01-01-lab.md, src/_posts/addons/2000-01-01-scalingo-openvpn.md, src/_posts/addons/2000-01-01-scalingo-vpn-ipsec.md, src/_posts/addons/2000-01-01-tcp-gateway.md
https://scalingo.slack.com/archives/CRC7L0XM2/p1659360643991349
=> feat: remove blank pages

src/_posts/databases/postgresql/2000-01-01-extensions.md
update from version 2.5.5 to 3.1.3
=> update postgis version

src/_posts/platform/deployment/2000-01-01-deploy-with-git.md, src/_posts/platform/getting-started/2000-01-01-troubleshooting-ssh.md
=> feature(git-push): Support of main branch for git push

src/_includes/registry_endpoints.md, src/_posts/addons/scalingo-docker-image/2000-01-01-start.md, src/_posts/platform/internals/2000-01-01-regions.md
=> fix(docker-addon): Improve docker addon page

src/changelog/cli/_posts/2022-08-29-1-24-2.md
Tweet:
> [Changelog] CLI - Release of version 1.24.2 https://cli.scalingo.com - More news at https://changelog.scalingo.com #cli #paas #changelog #bugfix
=> docs(changelog): CLI v1.24.2

src/_posts/platform/deployment/2000-01-01-deploy-with-github.md, src/_posts/platform/deployment/2000-01-01-deploy-with-gitlab.md
=> fix(cli): Update examples to work with incoming update for the CLI

src/_posts/platform/getting-started/2000-01-01-getting-started-with-elk.md
Related to: https://github.com/elastic/curator/issues/1587
=> fix(curator): update curator version

src/changelog/buildpacks/_posts/2022-09-23-php-redis-ext-5.3.7.md
Following up https://github.com/Scalingo/appsdeck-builder/pull/284
=> chore(php-buildpack): update redis extension to 5.3.7

src/changelog/buildpacks/_posts/2022-09-23-php-composer-2.4.2.md
https://semver.scalingo.com/composer-scalingo-18/resolve/2.2
https://semver.scalingo.com/composer-scalingo-18/resolve/2.3
https://semver.scalingo.com/composer-scalingo-18/resolve/2.4
https://semver.scalingo.com/composer-scalingo-20/resolve/2.2
https://semver.scalingo.com/composer-scalingo-20/resolve/2.3
https://semver.scalingo.com/composer-scalingo-20/resolve/2.4
It's all been released.
Fixes https://github.com/Scalingo/php-buildpack/issues/267
=> Fix/php buildpack/254/composer 2.2.18 2.3.10 2.4.2

src/_posts/security/procedures/2000-01-01-gdpr.md
DPA is now included in the Terms of Service
[ITT-143]
[ITT-143]: https://scalingo.atlassian.net/browse/ITT-143?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove the procedure to get a signed DPA

src/_posts/platform/getting-started/2000-01-01-free-trial.md
=> docs(free trial): add paragraph about review apps in free trial

src/_posts/platform/deployment/2000-01-01-deployment-process.md, src/_posts/platform/deployment/buildpacks/2000-01-01-apt.md, src/_posts/platform/deployment/buildpacks/2000-01-01-cairo.md, src/_posts/platform/deployment/buildpacks/2000-01-01-custom.md, src/_posts/platform/deployment/buildpacks/2000-01-01-jemalloc.md, src/_posts/platform/deployment/buildpacks/2000-01-01-nginx.md, src/_posts/platform/deployment/buildpacks/2000-01-01-ssh-key.md, src/_posts/platform/deployment/continuous-integration/2000-01-01-deploy-scalingo-from-travis-ci.md, src/_posts/platform/getting-started/2000-01-01-common-deployment-errors.md, src/_posts/platform/getting-started/2000-01-01-first-steps.md, src/_posts/platform/getting-started/2000-01-01-getting-started-with-elk.md, src/_posts/platform/getting-started/2000-01-01-getting-started-with-grafana.md, src/_posts/platform/getting-started/2000-01-01-getting-started-with-modsecurity.md, src/_posts/platform/getting-started/2000-01-01-getting-started-with-wordpress.md, src/_posts/platform/getting-started/2000-01-01-heroku-compatibility.md, src/_posts/platform/getting-started/2000-01-01-setup-git-windows.md, src/_posts/platform/getting-started/2000-01-01-setup-ssh-linux.md, src/_posts/platform/getting-started/2000-01-01-setup-ssh-macos.md, src/_posts/platform/getting-started/2000-01-01-setup-ssh-windows.md, src/_posts/platform/getting-started/2000-01-01-troubleshooting-ssh.md
Related to [SRE-756]
[SRE-756]: https://scalingo.atlassian.net/browse/SRE-756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(documentation): Fixing spelling and grammar mistakes

src/changelog/databases/_posts/2022-10-18-redis.7.0.5-1.md
=> 2022-10-18-redis.7.0.5-1.md

src/_posts/languages/python/2000-01-01-start.md, src/changelog/buildpacks/_posts/2022-10-25-python-3.10.8.md
Fix https://github.com/Scalingo/python-buildpack/issues/67
=> docs(changelog): add support for Python 3.7.15, 3.8.15, 3.9.15 and 3.10.8

src/_posts/platform/app/2000-01-01-scm-integration.md
=> Add github actions support

README.md, src/_posts/platform/cli/2000-01-01-features.md
Added this command that might be useful to documentation, and updated the docker-compose of readme with docker compose.
=> feat: add scalingo self/whoami command

src/_posts/platform/app/2000-01-01-log-drain.md
Will be merged the 15th of November 2022.
Fix #1802
=> docs(log-drain): remove Logentries

src/_posts/platform/deployment/buildpacks/2000-01-01-custom.md
=> Private buildpack section

src/_posts/security/procedures/2000-01-01-external-testing.md
Ping @aurelien-reeves-scalingo
=> Be explicit about business hours

src/_posts/languages/elixir/2000-01-01-start.md
Adding to the docs a link from a community member explaining how to deploy Phoenix 1.6
=> elixir-1-6-tutorial-for-stack-20

src/_posts/platform/app/2000-01-01-custom-error-page.md
=> fix: add missing s

src/_includes/database_backups.md, src/_posts/databases/elasticsearch/2000-01-01-start.md, src/_posts/databases/influxdb/2000-01-01-start.md, src/_posts/databases/mongodb/2000-01-01-start.md, src/_posts/databases/mysql/2000-01-01-start.md, src/_posts/databases/postgresql/2000-01-01-extensions.md, src/_posts/databases/postgresql/2000-01-01-start.md, src/_posts/databases/redis/2000-01-01-start.md, src/_posts/platform/cli/2000-01-01-introduction.md, src/_posts/platform/internals/2000-01-01-container-sizes.md, src/_posts/platform/internals/2000-01-01-regions.md, src/_posts/platform/internals/stacks/2000-01-01-scalingo-14-stack.md, src/_posts/platform/internals/stacks/2000-01-01-scalingo-18-stack.md, src/_posts/platform/internals/stacks/2000-01-01-scalingo-20-stack.md, src/_posts/platform/internals/stacks/2000-01-01-stacks.md, src/app/styles/index.postcss.css
=> fix: small screen words breaking, table & code too large

src/_posts/databases/mysql/2000-01-01-start.md
=> docs(MySQL): mention v8 is HA prerequisites

src/_posts/platform/getting-started/2000-01-01-first-steps.md
Doing demo of updating documentation
=> Remove old dashboard link

src/_posts/platform/databases/2000-01-01-access.md
=> docs: add warning about db variable value use

src/_posts/languages/go/2000-01-01-start.md, src/changelog/buildpacks/_posts/2022-12-13-go-1.19.3.md
Fix https://github.com/Scalingo/go-buildpack/issues/25
=> docs(changelog): Go 1.19.3

src/_posts/databases/mongodb/2000-01-01-dump-restore.md
fix #1746 
Changes can be seen here : 
https://documentation-service-pr1856.osc-fr1.scalingo.io/databases/mongodb/dump-restore#dump-and-restore-with-force-tls
=> feat: add flags for ssl mongodump and mongorestore

src/_posts/platform/cli/2000-01-01-features.md, src/changelog/api/_posts/2023-01-05-send-signal.md, src/changelog/cli/_posts/2023-01-05-1-27-0.md
Must be merged after: https://github.com/Scalingo/cli/pull/841
Fix #1877
=> feat(send-signal): added documentation about command send-signal

_config.yml
Add the new sample Go for the Gin framework
=> feat(sample): add sample go gin

src/_posts/languages/nodejs/2000-01-01-start.md
=> Add required config for Vite

src/_posts/platform/app/2000-01-01-send-signal.md
=> feat(send-signal): new documentation page relative to the feature send signal

src/_posts/languages/ruby/2000-01-01-start.md
Information source is https://scalingo.slack.com/archives/C03T384J3/p1674560927678509
=> Update supported Ruby versions

src/_posts/security/bulletins/2023-01-01-SSB-2023-001.md
[VUL-105] [SECINC-43]
[VUL-105]: https://scalingo.atlassian.net/browse/VUL-105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SECINC-43]: https://scalingo.atlassian.net/browse/SECINC-43?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SSB-2023-001: first version

src/_posts/compliance/2000-01-01-hds.md
First proposal to address the "point de contact" questions that keep coming.
Please let me know if it seems ok for you, if something needs to be updated, or if something is missing :)
=> fix(hds compliance): add a FAQ entry about 'point de contact'

src/_posts/platform/app/2000-01-01-tasks.md
=> feat: add en entry about one off limitation per app

src/_posts/platform/deployment/2000-01-01-deploy-with-git.md
Related to https://github.com/Scalingo/git-repository-core/issues/246
=> fix(git-deploy): Add known issue with git clone and master branch

src/_posts/languages/java/2000-01-01-spring-boot.md
=> docs(Spring Boot): port needs to be defined for both JAR and WAR

src/_posts/platform/app/2000-01-01-static-files-hosting.md, src/index.md
=> feat(static-site): detail the jekyll hosting procedure

src/_posts/platform/deployment/buildpacks/2000-01-01-nginx.md
=> docs(Nginx): mention Nginx playground

src/_posts/languages/python/django/2000-01-01-start.md
=> feat(django): add doc on automatic db migrations for django

src/_posts/languages/nodejs/2000-01-01-angularjs.md, src/_posts/languages/nodejs/2000-01-01-start.md, src/_posts/platform/app/2000-01-01-jekyll.md, src/_posts/platform/app/2000-01-01-static-files-hosting.md
=> docs(angularjs): instruction to deploy this framework

src/_posts/platform/app/2000-01-01-tasks.md
=> add documentation about the new one-off containers limitation per account

src/_posts/languages/php/2000-01-01-start.md
=> docs(php-buildpack): Better documentation for rate limiting with PHP

src/_layouts/default_with_main.html
https://github.com/Scalingo/project-items/issues/86
=> feat(misc) Changelog, responsiveness

src/changelog/databases/_posts/2023-03-06-redis.7.0.8-1.markdown
=> changelog for redis 7.0.8-1

README.md, src/_plugins/jekyll-dirname-generator.rb
fix https://github.com/Scalingo/documentation/issues/1980
=> fix: duplication of pages

src/_posts/platform/app/2000-01-01-autoscaler.md
=> fix(documentation): typo in the autoscaling value

src/_posts/platform/app/2000-01-01-postdeploy-hook.md
=> docs(postdeploy): add instructions to notify Sentry

src/_posts/platform/deployment/buildpacks/2000-01-01-wkhtmltopdf.md
=> docs(wkhtmltopdf): add warning to mention deprecation

src/_posts/security/cryptography/2000-01-01-ssh.md
Related to https://github.com/Scalingo/appsdeck-auth/issues/190
=> [SSH] Re add algorithms to keep compatibility with standard tools

src/_posts/platform/app/2000-01-01-log-drain.md
This PR brings more information about the log-drains usage on Scalingo.
And also bring a configuration help for Logtail usage.
=> feat(log-drains): bring more information about log-drains usage

src/changelog/features/_posts/2023-04-05-log-drains-logtail-integration.md, src/changelog/log_drains/_posts/2023-04-05-logtail-compatibility.md
This PR bring a new changelog dealting about the new log-drains compatibility with Logtail.
=> docs(changelog): add new changelog about the log-drains compatibility with Logtail

src/_posts/platform/app/2000-01-01-secret-file-in-app.md
We often say that one-off are a copies of what is deployed, but there are some caveats.
=> Note on runtime and secret file

src/changelog/databases/_posts/2023-05-03-mysql-8.0.33-1.md
ref https://github.com/Scalingo/appsdeck-database/issues/2783
=> chore: add changelog entry for mysql 8.0.33-1

src/changelog/buildpacks/_posts/2023-05-05-nodejs.md
https://semver.scalingo.com/node/versions
=> chore(nodejs-buildpack): sync with upstream

src/_posts/platform/deployment/2000-01-01-deploy-with-github.md
=> fix(cli): wrong manual deploy command

src/_posts/platform/app/2000-01-01-review-apps.md
=> docs(review-apps): clarify what is copied from parent app

src/_posts/languages/nodejs/2000-01-01-start.md
=> docs(nodejs): catch SIGTERM with yarn

src/_posts/addons/scalingo-openvpn/2000-01-01-start.md
Related to recent support conversation.
=> docs(openvpn): specify what traffic is routed to the VPN

src/_posts/platform/app/2000-01-01-custom-error-page.md
=> docs(custom-error-page): restart app after set env

src/_posts/compliance/2000-01-01-hds.md, src/_posts/compliance/2000-01-01-iso27001.md, src/_posts/compliance/2000-01-01-rgesn.md
New page is here: https://documentation-service-pr2117.osc-fr1.scalingo.io/compliance/rgesn
=> docs(compliance): add RGESN answers

src/_posts/platform/app/2000-01-01-review-apps.md
Please review this PR and add the files on the CDN
=> Review Apps from forks

.github/dependabot.yml, .sclng/metadata.toml
Jean is soon leaving the company
=> desp: Change dependabot from Jean to Cyrille

src/_posts/platform/app/2000-01-01-log-drain.md
=> docs(log-drains): Logtail is now Better Stack Logs

src/_posts/platform/app/2000-01-01-sending-emails.md
=> docs(sending-emails): Improve the page by updating the list of providers

src/_posts/platform/deployment/2000-01-01-cache.md, src/_posts/platform/deployment/2000-01-01-deploy-from-archive.md, src/_posts/platform/deployment/2000-01-01-deploy-java-jar-war.md, src/_posts/platform/deployment/2000-01-01-deploy-with-git.md, src/_posts/platform/deployment/2000-01-01-limits.md, src/_posts/platform/deployment/2000-01-01-one-click-deploy.md
=> docs(git-push): followTags Git option is not supported

src/_posts/platform/deployment/2000-01-01-deploy-with-gitlab.md
=> feat(gitlab): add note to set the Git strategy to clone to avoid remote error

src/_posts/languages/php/2000-01-01-start.md
It makes things more clear IMHO.
=> fix(php-buildpack): replace PHP versions list with a table

src/_includes/frontend_servers_open_ports_cloudflare.md, src/_posts/platform/app/2000-01-01-cloudflare-scalingo-app.md, src/_posts/platform/internals/2000-01-01-network.md
=> feat(networks): describe which ports are opened on our front-servers

src/_posts/languages/php/2000-01-01-laravel.md, src/_posts/languages/php/2000-01-01-symfony.md
=> docs(php): Nginx conf for additional entrypoints in Symfony and Laravel

src/changelog/buildpacks/_posts/2023-07-04-ruby-3.3.0-preview1.md
Fixes https://github.com/Scalingo/ruby-buildpack/issues/50
=> deps(ruby-buildpack): release of ruby 3.3.0-preview1

src/_posts/platform/internals/2000-01-01-network.md
=> docs(network): add precisions on how ports are used on the platform

src/_posts/platform/cli/2000-01-01-start.md
=> feat: explain how to remove cli

src/changelog/buildpacks/_posts/2023-07-27-nodejs-18.17.0.md
Related to https://github.com/Scalingo/nodejs-buildpack/issues/81
=> feat(changelog): new nodejs version 18.17.0

src/_includes/db_tunnel_requires_ssh.md, src/_posts/databases/mongodb/2000-01-01-dump-restore.md, src/_posts/databases/mysql/2000-01-01-dump-restore.md, src/_posts/databases/postgresql/2000-01-01-dump-restore.md, src/_posts/databases/redis/2000-01-01-dump-restore.md, src/_posts/platform/databases/2000-01-01-access.md
=> fix(databases): specify to setup ssh for db-tunnel

src/_posts/platform/app/2000-01-01-filesystem.md
=> docs(tmp disk size limit): add warning about file limitation

src/_includes/github_permission.md, src/_posts/platform/deployment/2000-01-01-deploy-with-github.md
=> fix(github_permission): add admin rights information

src/_posts/languages/php/2000-01-01-start.md
=> docs(php): explain how to enable DataDog Tracer and AppSec

src/_posts/languages/php/2000-01-01-start.md, src/_posts/platform/app/2000-01-01-datadog.md
=> fix(php): datadog page link

src/_posts/platform/app/2000-01-01-domain.md, src/changelog/infrastructure/_posts/2023-07-31-new-ips.markdown
Related to https://github.com/Scalingo/scalingo-outscale-terraform/issues/394
=> feature(infrastructure) Document new IPs on both osc-fr1 and osc-secnum-fr1 region

src/_posts/platform/getting-started/2000-01-01-getting-started-with-elk.md
=> fix(curator): update instructions to install curator

src/_posts/platform/app/2000-01-01-lifecycle-management.md
Add manual action to perform when this happen
=> SCM link is not updated when application is renamed

src/_posts/languages/nodejs/2000-01-01-puppeteer.md
=> docs(puppeteer): mention flag no-sandbox

src/_includes/dbclient_fetcher.md, src/_posts/platform/databases/2000-01-01-access.md
=> fix(dbclient-fetcher): specify available options

src/_posts/security/cryptography/2000-01-01-tls.md
=> fix(cryptography): documents supported TLS version on our front servers

src/_posts/platform/databases/2000-01-01-duplicate.md
=> fix(database): add doc about db duplicating

src/_posts/databases/mongodb/2000-01-01-start.md
Actually stalled regarding the situation with Mongo Inc.
Fix #954
=> docs(mongodb): wording + grammatical issues

src/_posts/platform/databases/2000-01-01-access.md
=> feat(databases): connect multiple apps on a database

src/_posts/platform/getting-started/2000-01-01-getting-started-with-metabase.md
Reworded some paragraphs and added some insights about Metabase deployment.
Fixes #2246
=> fix(documentation): improve Metabase documentation

src/_posts/platform/app/2000-01-01-lifecycle-management.md
=> fix(documentation): fix link syntax

src/_posts/platform/getting-started/2000-01-01-getting-started-with-wordpress.md
=> Update S3 method name WP

src/_posts/platform/app/2000-01-01-review-apps.md
=> docs(review apps): add info about manually deleting a review app

src/_posts/platform/getting-started/2000-01-01-free-trial.md
=> Mention the resources deletion after 30 days of the freetrial expiration

src/_posts/platform/getting-started/2000-01-01-getting-started-with-metabase.md
=> bugfix: wrong link

src/_posts/languages/java/2000-01-01-start.md, src/changelog/buildpacks/_posts/2023-10-30-java-maven-3.9.4.md, src/changelog/buildpacks/_posts/2023-10-30-java-maven-9.3.4.md
Fix https://github.com/Scalingo/java-buildpack/issues/8
=> fix(java-buildpack): upstream v73

src/_posts/platform/deployment/continuous-integration/2000-01-01-deploy-scalingo-from-circle-ci.md
The existing CircleCI config seems outdated and didn't work without the proposed changes for me with CircleCI config 2.1.
Hope this can help others to integrate Scalingo with their CI.
=> Update CircleCI default config

src/_posts/platform/deployment/buildpacks/2000-01-01-apt.md
See https://launchpad.net/ubuntu/focal/+package/poppler-utils
=> Fix typo in package name

src/_posts/databases/mysql/2000-01-01-dump-restore.md
=> fix(mysqldump): add option to ignore statistics column

src/_posts/databases/influxdb/2000-01-01-dump-restore.md
Hopefully the last PR related to that change
Sorry for the spam
=> Add missing ® after InfluxDB

src/_posts/platform/internals/2000-01-01-routing.md
=> feat(routing): add text/html as supported for gzip compression

src/_posts/languages/nodejs/2000-01-01-start.md, src/_posts/languages/ruby/rails/2000-01-01-start.md, src/changelog/buildpacks/_posts/2023-11-29-nodejs-20.10.0-21.2.0.md
Fix https://github.com/Scalingo/nodejs-buildpack/issues/96
=> feat(changelog): release of NodeJS 20.10.0 and 21.2.0

src/_posts/languages/ruby/rails/2000-01-01-start.md, src/changelog/buildpacks/_posts/2023-11-29-ruby-jruby-9.3.13.0-9.4.5.0.md
Fix https://github.com/Scalingo/ruby-buildpack/issues/54
=> feat(changelog): release of JRuby 9.3.13.0 and 9.4.5.0

src/_includes/nginx_versions.md, src/_posts/platform/deployment/buildpacks/2000-01-01-nginx.md
Updated according to semver.
Fix #2361
=> fix(nginx): fix available versions

src/_posts/languages/php/2000-01-01-start.md
=> docs(php): Scout APM support

src/_posts/databases/postgresql/2000-01-01-start.md
=> docs(postgresql): do not drop database

src/_posts/platform/app/2000-01-01-child-apps.md
=> docs(child-apps): remove wrong assertion about what it copies

src/changelog/databases/_posts/2023-12-22-mysql-8.0.35-1.md
=> doc(changelog): release new MySQL 8.0.35-1 version

src/_posts/platform/deployment/buildpacks/2000-01-01-cairo.md
Sorry I forgot to push this modification :facepalm:
=> fix(cairo): HTTPS address

src/_posts/languages/ruby/2000-01-01-start.md, src/changelog/buildpacks/_posts/2023-12-26-ruby-3.3.0.md
=> new(ruby): release new ruby version 3.3.0

src/changelog/databases/_posts/2023-12-26-redis.7.2.3-1.markdown
=> new(redis): release new redis versions 6.2.14 and 7.2.3

src/_posts/databases/mysql/2000-01-01-mysql-8-prerequisites.md
=> feat(mysql): add one command script to migrate on MySQL 8

src/_posts/platform/databases/2000-01-01-adminer.md
This is a Work In Progress, related to #2397 
~~I'll update it once we get the final links to the updated documentation for each DB.~~
~~The decommission warning looks like this:~~ (Update below)
~~I suggest the following plan:~~
=> fix(adminer): add decommission warning

src/_posts/languages/php/2000-01-01-start.md
Fix #2443 
There's another small change that shouldn't have been here but that has no consequences.
=> fix(php): fix PHP version selection example

src/_posts/platform/databases/2000-01-01-adminer.md
Also add a link to the security bulletin
=> fix(documentation): rewrite Adminer decommission warning

src/_posts/security/postmortems/2024-01-31-SPM-2024-002.md
Fix https://github.com/Scalingo/project-items/issues/552
=> feature(postmortem) Publish SPM-2024-002

src/_posts/security/postmortems/2024-01-02-SPM-2024-001.md
Fix https://github.com/Scalingo/project-items/issues/554
=> feature(postmortem) Publish SPM-2024-001

src/_posts/languages/python/django/2000-01-01-start.md
Superseeds #2468 to sign commits
=> docs(django): small refacto

src/_posts/platform/app/2000-01-01-environment.md
ticket: https://github.com/Scalingo/documentation/issues/2451
=> feat(documentation): Add HOSTNAME env var in documentation

src/_posts/platform/app/2000-01-01-collaborators.md
Explain rights of collaborators and how to manage them from dashboard
Note: I don't understand why i don't find my collaborator page in the search engine, is it linked to algolia ?
Fix https://github.com/Scalingo/documentation/issues/1799
=> feat(documentation): Add collaborators rights and dashboard managment

src/changelog/cli/_posts/2024-02-13-1.30.1.md
Related release: https://github.com/Scalingo/cli/releases/tag/1.30.1
=> feat(changelog): release of CLI 1.30.1

src/_posts/languages/go/2000-01-01-start.md, src/changelog/buildpacks/_posts/2024-03-08-go-1.22.0.md
Related to https://github.com/Scalingo/go-buildpack/pull/31
=> docs(changelog): Go 1.22.0

src/_posts/databases/postgresql/2000-01-01-accessing.md, src/_posts/databases/postgresql/2000-01-01-backing-up.md, src/_posts/databases/postgresql/2000-01-01-monitoring.md, src/_posts/databases/postgresql/2000-01-01-overview.md, src/_posts/databases/postgresql/2000-01-01-postgis.md, src/_posts/databases/postgresql/2000-01-01-restoring.md, src/_posts/databases/postgresql/2000-01-01-timescaledb.md, src/_posts/databases/postgresql/2000-01-01-troubleshooting.md, src/_posts/platform/databases/2000-01-01-adminer.md
=> Misc. fixes

src/_posts/databases/postgresql/2000-01-01-managing.md
Based on https://github.com/Scalingo/documentation/pull/2501, I've added CLI part for PG
=> feat(postgresql): add CLI part for user management | STORY-201

src/_posts/platform/app/2000-01-01-review-apps.md
Prevent misleading user into thinking that we suggest to store secrets in scalingo.json
Fix #2521
=> fix(#2521): Update 2000-01-01-review-apps.md

src/_posts/platform/cli/2000-01-01-start.md
and therefore, remove todo/manual task: `# replace MY-USERNAME by your username`
=> Update doc, use %userprofile% in windows cmd

src/changelog/databases/_posts/2024-04-02-admin-phpmyadmin-decommission.md, src/changelog/databases/_posts/2024-04-02-mysql-8.0.35-1-default.md
Add changelog for:
- MySQL new default version
- Adminer and phpMyAdmin instances decommission
=> chore: changelogs

src/_posts/languages/go/2000-01-01-start.md, src/_posts/languages/python/2000-01-01-start.md, src/changelog/buildpacks/_posts/2024-04-10-go-1.21.9-1.22.2.md, src/changelog/buildpacks/_posts/2024-04-10-nodejs-18.20.1-20.12.1-21.7.2.md, src/changelog/buildpacks/_posts/2024-04-10-python-3.11.9-3.12.3.md
Fix https://github.com/Scalingo/nodejs-buildpack/issues/107
Fix https://github.com/Scalingo/python-buildpack/issues/97
Fix https://github.com/Scalingo/go-buildpack/issues/32
=> chore(changelog,doc): update following misc. releases

src/_posts/languages/java/2000-01-01-start.md, src/changelog/buildpacks/_posts/2024-05-02-java-22.0.1-17.0.11-11.0.23-1.8.0_412.md
Fix #2550 
Fix https://github.com/Scalingo/buildpack-jvm-common/issues/42
Fix https://github.com/Scalingo/buildpack-jvm-common/issues/44
Files have been uploaded to Object Storage.
=> fix(java): update versions available and default config

src/_posts/languages/nodejs/2000-01-01-start.md
Add documentation about .npmrc based on https://devc…enter.heroku.com/articles/nodejs-support#configuring-npm
ticket: https://github.com/Scalingo/documentation/issues/1981
=> feat(node): Add documentation about .npmrc

src/_posts/platform/app/2000-01-01-app-manifest.md
Add documentation based on https://scalingo.com/blog/scalingo-json-formation
ticket: https://github.com/Scalingo/documentation/issues/2604
=> feat(review-apps): Add formation to Documentation

src/_posts/languages/php/2000-01-01-start.md
=> fix(php): fix erroneous WEB_CONCURRENCY value for M container

src/_includes/point_in_time_recovery.md, src/_posts/databases/postgresql/2000-01-01-backing-up.md, src/_posts/databases/postgresql/2000-01-01-restoring.md
=> docs(postgresql): explain PiTR on 'Restoring' page

src/_posts/platform/app/2000-01-01-review-apps.md
=> docs(review-apps): explain when a manual review app is deleted

src/_posts/databases/postgresql/2000-01-01-postgis.md, src/_posts/languages/ruby/rails/2000-01-01-start.md
=> docs(rails): work with gem 'activerecord-postgis-adapter'

src/_posts/platform/account/2000-01-01-manage.md
=> docs(account): explain password update with GitHub login

docker-compose.yml, src/_posts/databases/mysql/2000-01-01-accessing.md, src/_posts/databases/postgresql/2000-01-01-accessing.md
=> docs(mysql|postgresql): add command to connect when in one-off

src/_posts/languages/php/2000-01-01-symfony.md
=> docs(symfony): replace Encore with AssetMapper

src/_posts/databases/postgresql/2000-01-01-backing-up.md, src/_posts/databases/postgresql/2000-01-01-managing.md
=> docs(postgresql): details about major upgrade

src/_posts/2000-01-01-compliance.md, src/_posts/2000-01-01-security.md, src/_posts/2000-01-01-tools.md, src/_posts/tools/2000-01-01-software-development-kit.md
=> docs(tools): mention SDKs and Terraform provider

src/_posts/databases/postgresql/2000-01-01-managing.md
=> Add explanation about automatic 'ANALYZE' after a major upgrade

src/changelog/buildpacks/_posts/2024-07-04-nodejs-22.4.0.md, src/changelog/buildpacks/_posts/2024-07-04-ruby-jruby-9.3.15.0-9.4.8.0.md
Fix https://github.com/Scalingo/ruby-buildpack/issues/72
Fix https://github.com/Scalingo/nodejs-buildpack/issues/130
=> chore(nodejs,ruby): misc. releases

src/_posts/databases/postgresql/2000-01-01-managing.md
=> feat: add instructions to disable a PG extension

src/_posts/databases/mysql/2000-01-01-managing.md
=> feat(mysql): add doc about SQL modes

src/changelog/buildpacks/_posts/2024-07-11-nodejs-18.20.4-20.15.1-22.4.1.md, src/changelog/buildpacks/_posts/2024-07-11-ruby-3.3.4.md
Fix https://github.com/Scalingo/ruby-buildpack/issues/74
Fix https://github.com/Scalingo/nodejs-buildpack/issues/132
=> chore(changelog): misc. buildpack updates

src/_posts/databases/postgresql/2000-01-01-managing.md
Added details on the PostgreSQL updrade process.
=> Details on the upgrade process

README.md, assets/application.js
This PR allows us to directly search the docs.scalingo.com using a query string
Fix #2707
=> Search using query string

src/_posts/languages/php/2000-01-01-ips-filtering.md
While investigating #1042, I noticed these small nitpicks
=> docs(ips-filtering): titlize the titles

src/_posts/security/postmortems/2024-08-02-SPM-2024-003.md
Fix https://github.com/Scalingo/project-items/issues/672
=> feature(postmortem) Publish SPM-2024-003

src/_layouts/page.html
=> Only show CVSS base score for CVSS v4

src/_posts/languages/go/2000-01-01-start.md, src/_posts/languages/ruby/2000-01-01-start.md, src/changelog/buildpacks/_posts/2024-08-06-go-1.21.12-1.22.5.md, src/changelog/buildpacks/_posts/2024-08-06-ruby-3.3.5.md
Fix https://github.com/Scalingo/go-buildpack/issues/38
Fix https://github.com/Scalingo/ruby-buildpack/issues/76
=> chore(buildpacks): misc. updates

src/_posts/languages/go/2000-01-01-start.md, src/_posts/languages/python/2000-01-01-start.md, src/changelog/buildpacks/_posts/2024-08-08-go-1.21.13-1.22.6.md, src/changelog/buildpacks/_posts/2024-08-08-python-3.12.5.md
Fix https://github.com/Scalingo/python-buildpack/issues/109
Fix https://github.com/Scalingo/go-buildpack/issues/40
=> chore: misc. buildpacks updates

src/_posts/security/bulletins/2024-08-02-SSB-2024-004.md, src/_posts/security/bulletins/2024-08-05-SSB-2024-004.md
Requires https://github.com/Scalingo/documentation/pull/2738 to be merged
=> ssb-2024-004

src/_posts/platform/app/2000-01-01-slugignore.md
=> docs(slugignore): add mention of character range

src/_posts/languages/python/django/2000-01-01-start.md
=> feat: Add a section about Daphne in the Django getting started

src/_posts/platform/app/2000-01-01-force-https.md
=> docs(force-https): explain HSTS override

src/_posts/platform/getting-started/2000-01-01-free-trial.md
Fix https://github.com/Scalingo/documentation/issues/2716
=> feat: Document how to break out of the free trial

src/_posts/addons/scalingo-openvpn/2000-01-01-start.md
Fix https://github.com/Scalingo/documentation/issues/2680
=> feat: Document reserved IPs for the OpenVPN addon

src/changelog/dashboard/_posts/2024-09-05-session-magagement.markdown, src/changelog/dashboard/_posts/2024-09-10-session-magagement.markdown
We have updated our session management policies to improve security, following OWASP recommendations.
=> Changelog note for our new session policies

src/_posts/databases/mysql/2000-01-01-backing-up.md, src/_posts/databases/postgresql/2000-01-01-backing-up.md
Fixes issue https://github.com/Scalingo/documentation/issues/2790
=> Updated the wording of the backup timezone.

README.md, src/_posts/platform/internals/2000-01-01-regions.md
=> docs(internals): add SSH public keys fingerprints

src/_posts/platform/getting-started/2000-01-01-getting-started-with-elk.md
=> docs(elk): mention Kibana basic auth environment variables

src/_posts/platform/deployment/buildpacks/2000-01-01-graphicsmagick.md
=> docs(graphicsmagick): limit ImageMagick resources

src/_posts/platform/deployment/buildpacks/2000-01-01-apt.md
See https://github.com/Scalingo/documentation/issues/2831
=> [apt-buildpack] Document use of signed repos

src/_posts/platform/deployment/buildpacks/2000-01-01-jemalloc.md
I also updated our internal procedure so that we don't forget to update this page in the future.
=> docs(jemalloc): add missing versions

src/_posts/languages/python/2000-01-01-start.md
Fix https://github.com/Scalingo/python-buildpack/issues/119
=> fix(python): update start page

src/_posts/languages/nodejs/2000-01-01-start.md, src/_posts/languages/nodejs/2000-01-01-yarn-2.md
See https://github.com/Scalingo/documentation/issues/2839
=> [Node.js] Confusion about how to prune devDependencies

src/_posts/platform/internals/2000-01-01-router-error-codes.md, src/_posts/platform/internals/2000-01-01-routing.md
=> docs(routing): explain HTTP 413 error

src/_posts/databases/mysql/2000-01-01-accessing.md, src/_posts/databases/mysql/2000-01-01-backing-up.md, src/_posts/databases/mysql/2000-01-01-connecting.md, src/_posts/databases/mysql/2000-01-01-managing.md, src/_posts/databases/postgresql/2000-01-01-managing.md
https://www.notion.so/scalingooriginal/DOC-MySQL-Specific-Updated-documentation-bb593175adc54fbfbfa19a8b9bc77114
=> [STORY-679] doc(db dashboard): update mysql documentation

src/_posts/languages/nodejs/2000-01-01-start.md, src/_posts/languages/ruby/rails/2000-01-01-start.md, src/changelog/buildpacks/_posts/2024-11-04-nginx-modsecurity-coreruleset-4.8.0.md, src/changelog/buildpacks/_posts/2024-11-04-nodejs-22.11.0.md
Fix https://github.com/Scalingo/nodejs-buildpack/issues/152
Fix https://github.com/Scalingo/nginx-buildpack/issues/69
=> chore(nginx,nodejs): misc. updates

src/_posts/languages/go/2000-01-01-start.md, src/changelog/buildpacks/_posts/2024-11-14-go-1.23.3-1.22.9.md, src/changelog/buildpacks/_posts/2024-11-14-nodejs-18.20.5-23.2.0.md
Fix https://github.com/Scalingo/nodejs-buildpack/issues/154
Fix https://github.com/Scalingo/go-buildpack/issues/50
=> chore(go-buildpack,nodejs-buildpack): misc. releases

redirections.yml, src/_posts/databases/postgresql/2000-01-01-upgrading.md
Apply fixes from #2882 review, since it was merged too quickly :disappointed:
=> fix(postgresql): apply fixes from review

src/_posts/languages/python/2000-01-01-start.md, src/changelog/buildpacks/_posts/2024-12-09-nginx-modsecurity-coreruleset-4.9.0.md, src/changelog/buildpacks/_posts/2024-12-09-nodejs-22.12.0.md, src/changelog/buildpacks/_posts/2024-12-09-python-3.10.16-3.11.11-3.12.8-3.13.1.md
Fix https://github.com/Scalingo/python-buildpack/issues/121
Fix https://github.com/Scalingo/nodejs-buildpack/issues/158
Fix https://github.com/Scalingo/nginx-buildpack/issues/72
=> chore: update misc. builpdacks

src/_posts/languages/elixir/2000-01-01-start.md
Updates link to elixir blog post to version 1.7
Fixes issue #2872
=> Update link to elixir tutorial to version 1.7

src/_posts/databases/mysql/2000-01-01-overview.md
... and fix some grammar.
Fixes issue #2908
=> fix(mysql): Specify the Community Edition of MySQL

src/_posts/platform/getting-started/2000-01-01-common-deployment-errors.md
=> feat: Add information about Archive too large deployment error

src/_posts/platform/app/2000-01-01-app-manifest.md
=> docs(app-manifest): replace addon name by ID

src/_posts/languages/python/2000-01-01-start.md, src/changelog/buildpacks/_posts/2024-12-16-nodejs-23.4.0.md, src/changelog/buildpacks/_posts/2024-12-16-python-default-3.13.md
Related to https://github.com/Scalingo/nodejs-buildpack/issues/160
Related to https://github.com/Scalingo/python-buildpack/issues/123
=> chore(nodejs-buildpack, python-buildpack): buildpack updates

src/_posts/platform/account/2000-01-01-manage.md, src/_posts/platform/internals/2000-01-01-billing.md
Update billing documentation related to failed payment retries management
=> Update billing documentation

src/_posts/platform/app/2000-01-01-collaborators.md
- Updated "list collaborators" section to point to new iam page
- Some wording corrections (according to the draft attached to the story)
=> [STORY-1075] Document new collaborators page

src/_posts/security/overview/2000-01-01-incident-support.md
Adjust the support availability window to align with the hours displayed on our website.
=> Adjust our support availability window

redirections.yml, src/_posts/databases/mongodb/2000-01-01-studio3t.md
=> docs(studio3t): rename third party robo 3t to studio 3t

src/_includes/database_postgresql_extensions.md, src/_posts/databases/postgresql/2000-01-01-postgresql-anonymizer.md, src/changelog/databases/_posts/2025-01-24-postgresql-16.6.0-1.md
This PR prepare the documentation for the release of the new PostgreSQL version 16 and the new extension PostgreSQL Anonymizer with some examples and how our beloved users can enable it.
=> [STORY-989] feat(pg): prepare release postgresql 16 and PostgreSQL Anonymizer

src/_posts/databases/postgresql/2000-01-01-upgrading.md
=> feat(postgresql): mention app maintenance mode during upgrade

src/_posts/languages/python/2000-01-01-start.md, src/changelog/buildpacks/_posts/2025-02-17-nodejs-20.18.3-22.14.0-23.8.0.md, src/changelog/buildpacks/_posts/2025-02-17-python-3.12.9-3.13.2.md
Fix https://github.com/Scalingo/nodejs-buildpack/issues/170
Fix https://github.com/Scalingo/python-buildpack/issues/132
=> chore(nodejs,python): buildpack updates

src/_posts/platform/getting-started/2000-01-01-setup-ssh-linux.md, src/_posts/platform/getting-started/2000-01-01-setup-ssh-macos.md, src/_posts/platform/getting-started/2000-01-01-setup-ssh-windows.md
Addition [2976](https://github.com/Scalingo/documentation/issues/2976)
=> Adding an Existing SSH Key to the SSH Agent in Documentation

src/_posts/languages/php/2000-01-01-dependencies.md, src/changelog/buildpacks/_posts/2025-02-24-nodejs-18.20.7.md, src/changelog/buildpacks/_posts/2025-02-25-nginx-owasp-modsecurity-3.0.14.md, src/changelog/buildpacks/_posts/2025-02-25-php-composer-2.8.6.md
Fix https://github.com/Scalingo/nodejs-buildpack/issues/172
Fix https://github.com/Scalingo/php-buildpack/issues/490
Fix https://github.com/Scalingo/nginx-buildpack/issues/81
=> chore: misc. buildpack updates

src/changelog/databases/_posts/2025-03-06-redis.7.2.7-1.md
=> release(redis): new version 7.2.7-1

src/_posts/security/postmortems/2025-03-11-SPM-2025-001.md
Fix https://github.com/Scalingo/project-items/issues/804
=> feat(postmortem): DDoS attack 2025-03-11

src/_posts/databases/2000-01-01-overview.md
Removed content is detailed in https://doc.scalingo.com/databases/backup-policies
=> fix(databases): remove duplicate content

src/_posts/languages/php/2000-01-01-symfony.md
Fix https://github.com/Scalingo/documentation/issues/3103
=> feat: Document how to access database over TLS with Symfony

src/_posts/platform/getting-started/2000-01-01-getting-started-with-wordpress.md
Issue : https://github.com/Scalingo/documentation/issues/3095
=> Add content about setting up Wordpress for Scalingo using other S3 providers

src/_posts/languages/php/2000-01-01-dependencies.md, src/changelog/buildpacks/_posts/2025-04-04-nodejs-23.11.0.md, src/changelog/buildpacks/_posts/2025-04-07-php-composer-2.8.8.md
Fix https://github.com/Scalingo/nodejs-buildpack/issues/181
=> chore(nodejs,php): updates

src/_posts/databases/postgresql/2000-01-01-overview.md
Related to https://github.com/Scalingo/documentation/pull/3117
=> chore(postgresql): update available versions

src/_includes/nginx_versions.md, src/_posts/languages/ruby/2000-01-01-start.md, src/changelog/buildpacks/_posts/2025-04-22-nginx-1.27.5.md, src/changelog/buildpacks/_posts/2025-04-22-ruby-3.3.8-3.4.3.md
Fix https://github.com/Scalingo/ruby-buildpack/issues/106
Fix https://github.com/Scalingo/nginx-buildpack/issues/87
nginx files have been uploaded to ObjectStorage:
- `scalingo-20`: https://semver.scalingo.com/nginx-scalingo-20/resolve/1.27
- `scalingo-22`: https://semver.scalingo.com/nginx-scalingo-22/resolve/1.27
=> chore(nginx,ruby): updates

src/_includes/nginx_versions.md, src/_posts/languages/php/2000-01-01-start.md, src/changelog/buildpacks/_posts/2025-05-09-nginx-1.28.0.md, src/changelog/buildpacks/_posts/2025-05-09-nginx-modsecurity-coreruleset-4.14.0.md, src/changelog/buildpacks/_posts/2025-05-09-nodejs-24.0.0.md, src/changelog/buildpacks/_posts/2025-05-09-php-8.3.21-8.4.7.md, src/changelog/buildpacks/_posts/2025-05-09-ruby-jruby-9.4.12.0-9.4.12.1-10.0.0.0-10.0.0.1.md
Fix https://github.com/Scalingo/php-buildpack/issues/501
Fix https://github.com/Scalingo/nodejs-buildpack/issues/185
Fix https://github.com/Scalingo/ruby-buildpack/issues/108
Fix https://github.com/Scalingo/nginx-buildpack/issues/88
Fix https://github.com/Scalingo/nginx-buildpack/issues/89
=> chore(nodejs,php,ruby): updates

src/_posts/languages/go/2000-01-01-start.md, src/_posts/languages/php/2000-01-01-dependencies.md, src/_posts/languages/ruby/2000-01-01-start.md, src/changelog/buildpacks/_posts/2025-05-15-go-1.23.9-1.24.3.md, src/changelog/buildpacks/_posts/2025-05-15-php-composer-2.8.9.md, src/changelog/buildpacks/_posts/2025-05-15-ruby-3.4.4.md
Fix https://github.com/Scalingo/ruby-buildpack/issues/110
Fix https://github.com/Scalingo/go-buildpack/issues/60
Fix https://github.com/Scalingo/php-buildpack/issues/504
=> chore(go-buildpack,ruby-buildpack): misc. releases

src/_posts/languages/python/2000-01-01-start.md, src/changelog/buildpacks/_posts/2025-06-05-nodejs-22.16.0-24.1.0.md, src/changelog/buildpacks/_posts/2025-06-05-python-3.10.18-3.11.13-3.12.11-3.13.4.md
Related to https://github.com/Scalingo/nodejs-buildpack/issues/187
Related to https://github.com/Scalingo/python-buildpack/issues/142
=> chore(nodejs,python): misc. updates

src/_posts/security/postmortems/2025-04-07-SPM-2025-002.md
Fix https://github.com/Scalingo/project-items/issues/858
=> feat(postmortem) Publish SPM-2025-002

src/_posts/platform/app/2000-01-01-notification.md
Reflect changes made by https://github.com/Scalingo/api/pull/2685
Document the new`collaborator_role_changed` event
=> [STORY-1429] Add a new event for collaborator role change

src/_posts/databases/opensearch/guides/ingesting-logs/2000-01-01-opensearch-dashboards.md
I do not know if this worth for all, but a customer and myself had to follow these exact steps for a successful OpenSearch Dashboards deploy.
=> Update the first OpenSearch Dashboards depoly

src/_posts/security/procedures/2000-01-01-external-testing.md
[IRQ-472] fix/udpate pentest procedure
Based on: https://scalingo.atlassian.net/browse/IRQ-472
Need to better clarify that we want FIRST to use Scalingo's template and SECOND use customer's one.
[IRQ-472]: https://scalingo.atlassian.net/browse/IRQ-472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [IRQ-472] fix/udpate pentest procedure

src/_posts/databases/opensearch/guides/ingesting-logs/2000-01-01-logstash.md
=> fix: wrong URL

src/changelog/buildpacks/_posts/2025-08-06-php-apcu-ext-5.1.26.md
=> fix(changelog): fix wrong date in changelog entry

src/_posts/security/postmortems/2025-08-02-SPM-2025-003.md
fix https://github.com/Scalingo/project-items/issues/875
=> feat(postmortem): Publish SPM-2025-003

src/_posts/platform/deployment/2000-01-01-deploy-with-gitlab.md
=> feat(gitlab-scm): Mention Group access token support

src/_posts/languages/ruby/2000-01-01-start.md
Supersedes #3325
Thanks @goulvench
=> fix: update WEB_CONCURRENCY table

src/_posts/platform/app/2000-01-01-metrics.md
=> Add behavior OOM

src/_posts/databases/mysql/2000-01-01-connecting.md, src/_posts/languages/ruby/rails/2000-01-01-start.md
* Automated ENV var sub for mysql2 gem
================================================================================
=> feat(misc): Update MySQL rails config
